### ISSUE TITLE
malloc error on shutdown (OSX only)

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#103]
This does not reproduce on Linux or Windows, and appears consistently on OSX once the blockchain has achieved some (unknown, less than 164,500 blocks) size. The shutdown appears to succeed and subsequent startups work correctly.
```
Please wait while server is stopping...
Server stopped cleanly.
Please wait while files are unmapped...
18:27:41.290825 INFO [database] Unmapping: "blockchain/stealth_rows"
18:27:41.290976 INFO [database] Unmapping: "blockchain/stealth_index"
18:27:41.291075 INFO [database] Unmapping: "blockchain/history_rows"
18:27:41.291233 INFO [database] Unmapping: "blockchain/history_lookup"
18:27:41.293490 INFO [database] Unmapping: "blockchain/txs"
18:27:41.295112 INFO [database] Unmapping: "blockchain/spends"
18:27:41.297537 INFO [database] Unmapping: "blockchain/blocks_rows"
18:27:41.297644 INFO [database] Unmapping: "blockchain/blocks_lookup"
bs(1312,0x7fff7a6fc300) malloc: *** error for object 0x7fb66c81fa08: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Please wait while server is stopping...
Abort trap: 6
```

**Comment by evoskuil** [comment]
@skaht - Any chance I could get you to debug this, given you have been building for OSX?

**Comment by skaht** [comment]
I'm also getting similar anomalous behavior last night with the latest source code published.  Thought I would sleep on the issue for day. The server was running quite hot, so I performed a CNTL-C. Here is a cut-n-paste from running bitcoin-server last night.

23:37:19.386286 INFO [poller] Block #485733 00000000034dc444cf7a8e425fc9c6ee9173fdd9c7e08438ac76e2a067a94ec9
23:37:23.941112 INFO [poller] Block #485734 000000000000166c3e89d984eca00d88e98f09ab7f9e41328cbd60c2f90e26e6
23:37:25.586200 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:37:27.012180 INFO [protocol] Connected to peer [54.149.133.4:18333] on slot [7] (6 total)
^CPlease wait while server is stopping...
Server stopped cleanly.
Please wait while files are unmapped...
23:40:18.865582 INFO [database] Unmapping: "blockchain/stealth_rows"
23:40:18.865697 INFO [database] Unmapping: "blockchain/stealth_index"
23:40:18.865771 INFO [database] Unmapping: "blockchain/history_rows"
23:40:18.868607 INFO [database] Unmapping: "blockchain/history_lookup"
23:40:18.869388 INFO [database] Unmapping: "blockchain/txs"
23:40:18.883097 INFO [database] Unmapping: "blockchain/spends"
23:40:18.892482 INFO [database] Unmapping: "blockchain/blocks_rows"
23:40:18.892551 INFO [database] Unmapping: "blockchain/blocks_lookup"
bs(43588,0x7fff74fe9300) malloc: *** error for object 0x7fbb59813408: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Please wait while server is stopping...
Abort

Libconsensus doesn't compile nicely on the Mac. The current build at this end was accomplished by:

./install.sh --disable-shared ---prefix=/Users/XXX/Projects/BX/bitcoin-server/test --build-dir=/Users/XXX/Projects/BX/bitcoin-server/build --without-consensus --build-boost --enable-testnet

**Comment by evoskuil** [comment]
Yes, that's the same shutdown error that I posted above. My build was also `--without-consensus`. 

`libbitcoin-consensus` builds cleanly on OSX on Travis, if you are having an issue with that please post more details to the that repo's issue board.

Are you sure you didn't have a prefix issue (there are three leading hyphens in `---prefix=...`).

**Comment by skaht** [comment]
I'll do the builds with consensus and post the results shortly. Is there an existing open issue number to post the results at?

It could take me months to debug this issue because I don't have *.xcodeproj Xcode builds to make it easy to trap the issue.  Plus I got a huge learning curve ahead with using Xcode IDE. The last time I really did any serious debugging was on an SGI about 17 years ago.   Over the last six months I was trying to get my head around libbitcoin dependencies by rolling custom build scripts.  This was so one day I could have a chance at making a few *.xcodeproj as baby steps.

**Comment by evoskuil** [comment]
No, there are no open issues on `libbitcoin-consensus`.

I don't have a debug environment for OSX either, thought you might.

**Comment by evoskuil** [comment]
I just did a successful build using your command line (modulo the extra hyphen) but `--with-consensus` on OSX:
```sh
$ ./install.sh --disable-shared --prefix=/Users/Eric/bs-prefix-test --build-dir=/Users/Eric/bx-build-test --with-consensus --build-boost --enable-testnet
```
It completed and runs fine.

**Comment by skaht** [comment]
I'll be explicit with the application of the `--with-concensus` flag and see what happens this time around.  The following was the result of not being explicit:

`% ./install.sh --disable-shared --prefix=/Users/XXX/Projects/BX/bitcoin-server/test --build-dir=/Users/XXX/Projects/BX/bitcoin-server/build --build-boost --enable-testnet`

Failed during libbitcoin-blockchain configure:

configure: error: Package requirements (libbitcoin-consensus >= 1.0.0) were not met:

Package 'libbitcoin-consensus' requires 'libcrypto >= 1.0.1' but version of libcrypto is 0.9.8zd

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables bitcoin_consensus_CFLAGS
and bitcoin_consensus_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

FYSA - The Mac Homebrew package manage at this end has openssl 1.0.1l, 1.0.2, and 1.0.2d installed in the Cellar residing at /Users/XXX/usr/local/Homebrew/Cellar/openssl.

**Comment by skaht** [comment]
The build did complete successfully when I was explicit with the `--with-consensus` flag.  The following did work just fine:-)

`./install.sh --disable-shared --prefix=/Users/XXX/Projects/BX/bitcoin-server/test --build-dir=/Users/XXX/Projects/BX/bitcoin-server/build --build-boost --with-consensus --enable-testnet`

**Comment by evoskuil** [comment]
It's using `pkg-config` to locate `libcrypto` . When you use a prefix directory that directory is added to `PKG_CONFIG_PATH` by the installer. Since `libcrypto` is not referred to by a package in the `PKG_CONFIG_PATH` directories, `pkg-config` decides to look in system directories to resolve the reference. There it finds a reference to a crusty old version, which configure rejects based on version.

You need to either upgrade the system installation, set `PKG_CONFIG_PATH` appropriately, or the `bitcoin_consensus_[ ]` flags (basically what the error says).

**Comment by evoskuil** [comment]
Being explicit with the default `--with-consensus` should not make any difference.

If coincidentally you fixed the `---prefix=` issue then your prefix would start working. That may have prevented `pkg-config` form locating the old version in the system directories (which implies my description of its operation was slightly off above).

**Comment by skaht** [comment]
For libbitcoin-consensus and libbitcoin-blockchain, it looks like the work around for my older custom scripts was to explicitly set the following two environmental variables: crypto_CFLAGS, crypto_LIBS. Or set the variables when passed into the configure scripts for libbitcoin-consensus and libbitcoin-blockchain. I made a build script apart from Homebrew for openssl to ensure the custom build completed.

**Comment by skaht** [comment]
At the cost of a longer build the install.sh could be tweaked to also download and build the correct version of openssl.  The gist of the openssl script on the Mac is:

./Configure \
--prefix=$openssl_dir \
no-ssl2 \
zlib-dynamic \
shared \
enable-cms \
darwin64-x86_64-cc enable-ec_nistp_64_gcc_128

make depend
make
make test
make install

**Comment by skaht** [comment]
When I build bitcoin-server for the testnet using my own scripts the server behaved much better; albeit without consensus behaviors.  I will start working on the custom scripts tomorrow night again to see if I get different result with the latest code.  

Using the two install.sh programs, I'm also noticing that I can't get my bx testnet client to communicate to my local bitcoin-server.  Did not have this problem a few weeks back.  But have noticed the distribution bx.cfg and bs.cfg files have recently changed. 

Calling it a night...

**Comment by evoskuil** [comment]
What command(s) are you attempting between `bx` and `bs`?

**Comment by evoskuil** [comment]
I was avoiding the OpenSSL integration as it's a problem that will resolve itself once libbitcoinconsensus drops OpenSSL.

**Comment by skaht** [comment]
Figured out why bx was not talking to local bitcoin-server.  After compiling bx with `--enable-testnet` flag set, had to explicitly set `network = testnet`.  Otherwise, bx was always hitting the default mainnet bs server.

**Comment by evoskuil** [comment]
Cool, thanks for the update.

**Comment by evoskuil** [comment]
This should be resolved in master. I set up tracking on all dynamically-allocated objects and determine that the shutdown process was leaving unreleased instances in closures within the ASIO message queue. Changing the threadpool shutdown to wait for work completion resolved that issue, and I suspect that was the cause of this shutdown exception.

**Comment by skaht** [comment]
Makes sense. Hoping some of that programming Kung Fu rubs off...

**Comment by digitsu** [comment]
I am seeing a big jump in memory usage after block 191693 in the sync, which shot up to 9GB, and froze up my computer.

it didn’t seem to crash, but the memory pressure is pretty high.  Is this normally just something that should be expected during the sync or will running the server normally take up this much memory? (and thus a medium spec system with 8GB of ram won’t seem like enough) (I’m running on Macbook pro 2011, osx 10.10.

Thanks,

**Comment by evoskuil** [comment]
Note that this issue is **malloc error on shutdown (OSX only)**.

Please see https://github.com/libbitcoin/libbitcoin-server/issues/100.

**Comment by digitsu** [comment]
Apologies. I'm guilty of replying by mail. 




Yes the issue is resolved by just restarting. 









—
Regards,

**Comment by skaht** [comment]
My have posted a response in the wrong thread bitcoin-server behaviors on testnet, see https://github.com/libbitcoin/libbitcoin-server/issues/100#issuecomment-141345966.

**Comment by evoskuil** [comment]
This should be resolved on master, as the result of corrections to the cleanup of objects in the message queue at shutdown. We were previously terminating the message queue without letting all messages complete so as to unwind closures. Instance tracking confirms correct behavior.
