### ISSUE TITLE
Can't clear logs without restarting server.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#107]
Add log rotation feature.

**Comment by evoskuil** [comment]
Move to [Boost Test](http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/index.html) to resolve this and other logging issues.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin/issues/307

**Comment by RojavaCrypto** [comment]
Yes you can clear logs without restarting the server:

    echo > debug.log

Log continues on from there.

UNIX systems use the tool `logrotate` for this. Server programs don't normally do log rotation themselves.

http://www.linuxcommand.org/man_pages/logrotate8.html

**Comment by evoskuil** [comment]
There's also the issue of the Windows builds. If there's an in box way to do this I'd close this (but retain the boost.log task).

**Comment by RojavaCrypto** [comment]
logrotate also exists on Windows in cygwin package.

Also:

https://www.itefix.net/logwot8

https://sourceforge.net/projects/logrotatewin/

These are basic admin tools, so I'd expect other better solutions to exist for Windows. Also the specifics vary highly from setup to setup (what compression alg to use, where to put them, what to rename old files too, lots of options). It's better to stick with platform tools that will follow local convention.

**Comment by evoskuil** [comment]
Sounds good.
