### ISSUE TITLE
FAIL: libbitcoin_explorer_test_runner.sh

### ISSUE THREAD

**Issue by Abdullah114** [libbitcoin/libbitcoin-server#114]
After all dependencies were installed successfully and ran
`./autogen.sh`
` ./configure`
got following error:
> root@t410:/home/n/Desktop/libbitcoin-explorer# make check
>   CXX      src/src_libbitcoin_explorer_la-async_client.lo
  CXX      src/src_libbitcoin_explorer_la-callback_state.lo
  CXX      src/src_libbitcoin_explorer_la-dispatch.lo
  CXX      src/src_libbitcoin_explorer_la-display.lo
  CXX      src/src_libbitcoin_explorer_la-generated.lo
  CXX      src/src_libbitcoin_explorer_la-obelisk_client.lo
  CXX      src/src_libbitcoin_explorer_la-prop_tree.lo
  CXX      src/src_libbitcoin_explorer_la-utility.lo
  CXX      src/commands/src_libbitcoin_explorer_la-address-decode.lo
  CXX      src/commands/src_libbitcoin_explorer_la-address-embed.lo
...
...
  CXX      src/primitives/src_libbitcoin_explorer_la-wif.lo
  CXX      src/primitives/src_libbitcoin_explorer_la-wrapper.lo
  CXXLD    src/libbitcoin-explorer.la
  CXX      console/console_bx-main.o
  CXXLD    console/bx
make  test/libbitcoin_explorer_test
make[1]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
  CXX      test/test_libbitcoin_explorer_test-generated__broadcast.o
  CXX      test/test_libbitcoin_explorer_test-generated__find.o
  CXX      test/test_libbitcoin_explorer_test-generated__formerly.o
  CXX      test/test_libbitcoin_explorer_test-generated__symbol.o
  CXX      test/test_libbitcoin_explorer_test-main.o
  CXX      test/commands/test_libbitcoin_explorer_test-address-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-address-embed.o
  CXX      test/commands/test_libbitcoin_explorer_test-address-encode.o
  CXX      test/commands/test_libbitcoin_explorer_test-address-validate.o
  CXX      test/commands/test_libbitcoin_explorer_test-base16-decode.o
...
...
  CXX      test/commands/test_libbitcoin_explorer_test-watch-address.o
  CXX      test/commands/test_libbitcoin_explorer_test-watch-tx.o
  CXX      test/commands/test_libbitcoin_explorer_test-wif-to-ec.o
  CXX      test/commands/test_libbitcoin_explorer_test-wif-to-public.o
  CXX      test/commands/test_libbitcoin_explorer_test-wrap-decode.o
  CXX      test/commands/test_libbitcoin_explorer_test-wrap-encode.o
  CXX      test/primitives/test_libbitcoin_explorer_test-address.o
  CXX      test/primitives/test_libbitcoin_explorer_test-base58.o
  CXXLD    test/libbitcoin_explorer_test
make[1]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
make  check-TESTS
make[1]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
make[2]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
FAIL: libbitcoin_explorer_test_runner.sh
make[3]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
------------------------------------------------------------------------------------
Testsuite summary for libbitcoin-explorer 2.2.1
TOTAL: 1
PASS:  0
SKIP:  0
XFAIL: 0
FAIL:  1
XPASS: 0
ERROR: 0
------------------------------------------------------------------------------------
See ./test-suite.log
Please report to eric@voskuil.org
------------------------------------------------------------------------------------
make[2]: *** [test-suite.log] Error 1
make[2]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
make[1]: *** [check-TESTS] Error 2
make[1]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
make: *** [check-am] Error 2

**Comment by Abdullah114** [comment]
=================================================
   libbitcoin-explorer 2.2.1: ./test-suite.log
=================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: libbitcoin_explorer_test_runner.sh
========================================

/home/n/Desktop/libbitcoin-explorer/test/.libs/lt-libbitcoin_explorer_test: error while loading shared libraries: libb$

**Comment by Abdullah114** [comment]
following commands will fix the error described above.
> root@t410:/home/n/Desktop/libbitcoin-explorer# ldconfig
> root@t410:/home/n/Desktop/libbitcoin-explorer# 
root@t410:/home/n/Desktop/libbitcoin-explorer# ./libbitcoin_explorer_test_runner.sh 
Running 502 test cases...
Platform: linux
Compiler: GNU C++ version 4.8.2
STL     : GNU libstdc++ version 20140115
Boost   : 1.55.0
root@t410:/home/n/Desktop/libbitcoin-explorer# ./autogen.sh 
root@t410:/home/n/Desktop/libbitcoin-explorer# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
...
...
checking whether the linker accepts -fstack-protector-all... yes
checking whether C++ compiler accepts -fvisibility-hidden... no
checking whether C++ compiler accepts -fvisibility-inlines-hidden... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libbitcoin-explorer.pc
config.status: executing depfiles commands
config.status: executing libtool commands
root@t410:/home/n/Desktop/libbitcoin-explorer# make check
make  test/libbitcoin_explorer_test
make[1]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
make[1]: `test/libbitcoin_explorer_test' is up to date.
make[1]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
make  check-TESTS
make[1]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
make[2]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
PASS: libbitcoin_explorer_test_runner.sh
make[3]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
----------------------------------------------------------------------------------------------------------------------------
Testsuite summary for libbitcoin-explorer 2.2.1
----------------------------------------------------------------------------------------------------------------------------
TOTAL: 1
PASS:  1
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0
----------------------------------------------------------------------------------------------------------------------------
make[2]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
make[1]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
root@t410:/home/n/Desktop/libbitcoin-explorer# make install
...
...
 /bin/mkdir -p '/usr/local/etc/libbitcoin'
 /usr/bin/install -c -m 644 data/bx.cfg '/usr/local/etc/libbitcoin'
make[1]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
root@t410:/home/n/Desktop/libbitcoin-explorer#

**Comment by Abdullah114** [comment]
following commands will fix the error described above.
> ldconfig
> ./libbitcoin_explorer_test_runner.sh 
> ./autogen.sh 
> ./configure
> make check
> make install
> ldconfig

so will look something like:
> root@t410:/home/n/Desktop/libbitcoin-explorer# ldconfig
> root@t410:/home/n/Desktop/libbitcoin-explorer# 
root@t410:/home/n/Desktop/libbitcoin-explorer# ./libbitcoin_explorer_test_runner.sh 
Running 502 test cases...
Platform: linux
Compiler: GNU C++ version 4.8.2
STL     : GNU libstdc++ version 20140115
Boost   : 1.55.0
root@t410:/home/n/Desktop/libbitcoin-explorer# ./autogen.sh 
root@t410:/home/n/Desktop/libbitcoin-explorer# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
...
...
checking whether the linker accepts -fstack-protector-all... yes
checking whether C++ compiler accepts -fvisibility-hidden... no
checking whether C++ compiler accepts -fvisibility-inlines-hidden... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libbitcoin-explorer.pc
config.status: executing depfiles commands
config.status: executing libtool commands
root@t410:/home/n/Desktop/libbitcoin-explorer# make check
make  test/libbitcoin_explorer_test
make[1]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
make[1]: `test/libbitcoin_explorer_test' is up to date.
make[1]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
make  check-TESTS
make[1]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
make[2]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
PASS: libbitcoin_explorer_test_runner.sh
make[3]: Entering directory `/home/n/Desktop/libbitcoin-explorer'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
----------------------------------------------------------------------------------------------------------------------------
Testsuite summary for libbitcoin-explorer 2.2.1
----------------------------------------------------------------------------------------------------------------------------
TOTAL: 1
PASS:  1
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0
----------------------------------------------------------------------------------------------------------------------------
make[2]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
make[1]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
root@t410:/home/n/Desktop/libbitcoin-explorer# make install
...
...
 /bin/mkdir -p '/usr/local/etc/libbitcoin'
 /usr/bin/install -c -m 644 data/bx.cfg '/usr/local/etc/libbitcoin'
make[1]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
root@t410:/home/n/Desktop/libbitcoin-explorer#

**Comment by evoskuil** [comment]
Hi @Abdullah114, Note that this is the server (not explorer) repo. Is there a problem with the instructions?

**Comment by Abdullah114** [comment]
Hello @evoskuil , yes I got this problem while installing. In fact I wanted to install BX (libbitcoin-explorer), but it required me to install libbitcoin-server and libbitcoin-client. I followed the instructions from github and installed their respective dependencies, but received errors and installation was aborted. Further I fixed those errors as described above. Just wanted to share this if anyone would get the same error.

**Comment by evoskuil** [comment]
The build described above is for explorer, not for server (this repo). BX doesn't depend on server.

It's not clear to me what was broken or what was fixed above. The builds are extremely reliable and regularly tested.

**Comment by Abdullah114** [comment]
Sorry I wanted to posted this into wrong directory. As you mentioned this was error on explorer not on server.
`root@t410:/home/n/Desktop/libbitcoin-explorer# make check`

The problem was that when I ran 

> git clone https://github.com/libbitcoin/libbitcoin-explorer.git
cd libbitcoin-explorer
./autogen.sh
./configure
make check

I received an error:

'FAIL: libbitcoin_explorer_test_runner.sh'  (line #4 in the following code snippet)

> make check-TESTS
make[1]: Entering directory /home/n/Desktop/libbitcoin-explorer' make[2]: Entering directory/home/n/Desktop/libbitcoin-explorer'
FAIL: libbitcoin_explorer_test_runner.sh
make[3]: Entering directory /home/n/Desktop/libbitcoin-explorer' make[3]: Nothing to be done forall'.
make[3]: Leaving directory `/home/n/Desktop/libbitcoin-explorer'
Testsuite summary for libbitcoin-explorer 2.2.1
TOTAL: 1
PASS: 0
SKIP: 0
XFAIL: 0
FAIL: 1
XPASS: 0
ERROR: 0
See ./test-suite.log
Please report to eric@voskuil.org
make[2]: *** [test-suite.log] Error 1
make[2]: Leaving directory /home/n/Desktop/libbitcoin-explorer' make[1]: *** [check-TESTS] Error 2 make[1]: Leaving directory/home/n/Desktop/libbitcoin-explorer'
make: *** [check-am] Error 2

**Comment by evoskuil** [comment]
This is a test failure, not a build break. See the test output as described above. I suspect you are encountering intermittent failures on network functional tests.
