### ISSUE TITLE
bs.cfg read issues

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-server#118]
Did a fresh rebuild of bitcoin-server this evening for OS X the proper way. 

`% ./install.sh --disable-shared --prefix=/Users/XXX/Projects/BX/bitcoin-server/test --build-dir=/Users/XXX/Projects/BX/bitcoin-server/build --build-boost --with-consensus --enable-testnet`

I have the following environmental variable set by a login shell:

setenv BS_CONFIG   $HOME/Projects/BX/bitcoin-server/bs-testnet.cfg

I manually copied the template config file to the location specified by the environmental variable

`cp $HOME/Projects/BX/bitcoin-explorer/etc/libbitcoin/bs.cfg $HOME/Projects/BX/bitcoin-explorer/bx-testnet.cfg`

% bs
Error: unrecognised option 'general.blockchain_path'

So I go into the bx-testnet.cfg file and comment out "#blockchain_path = blockchain"

% bs
Error: unrecognised option 'general.history_height' 

I can keep on commenting out lines and the read error continues to move forward to the next uncommented line in the config file. Any recommendations?

**Comment by evoskuil** [comment]
You seem to be mixing BS and BX paths.

**Comment by skaht** [comment]
Sorry about my error posting the issue above.  Was running out of steam late last night the line below is what I should have been posted above. 

`cp $HOME/Projects/BX/bitcoin-server/etc/libbitcoin/bs.cfg $HOME/Projects/BX/bitcoin-server/bx-testnet.cfg`

I definitely got firm feedback that I was tweaking the correct file, because once I commented out a line the bitcoin-server executable would complain about the next config file line that was not commented out.  Just confirmed the behavior again to be absolutely certain. The issue is still the same at this end.

**Comment by evoskuil** [comment]
The command above still seems wrong. You are copying the default `bs.cfg` to `bx-testnet.cfg`.

But in any case, the error on `general.database_path` indicates your config file is invalid/outdated for BS. There is no `[general]` section in BS. BX on the other hand does have a `[general]` section, but it has no `blockchain_path` and no `history_height` (BX doesn't maintain a blockchain). The use of `[general]` in BS pre-dates the v2.1 release (see: 9f4d5ba9).

**Comment by skaht** [comment]
Found the issue.  Error was made at my end.  Was using a deprecated bs.cfg and used it as a template.

**Comment by evoskuil** [comment]
Cool, thanks.
