### ISSUE TITLE
build errors when using the Mac OSX install.sh

### ISSUE THREAD

**Issue by digitsu** [libbitcoin/libbitcoin-server#122]
I'm using the install.sh from:
$ wget https://raw.githubusercontent.com/libbitcoin/libbitcoin-server/version2/install.sh

managed to get to the compile of the final component, libbitcoin-server, but stops here,

config.status: executing libtool commands
  CXX      src/src_libbitcoin_server_la-dispatch.lo
  CXX      src/src_libbitcoin_server_la-message.lo
  CXX      src/src_libbitcoin_server_la-publisher.lo
  CXX      src/src_libbitcoin_server_la-server_node.lo
  CXX      src/src_libbitcoin_server_la-subscribe_manager.lo
  CXX      src/src_libbitcoin_server_la-worker.lo
  CXX      src/config/src_libbitcoin_server_la-config.lo
  CXX      src/config/src_libbitcoin_server_la-settings.lo
  CXX      src/service/src_libbitcoin_server_la-blockchain.lo
  CXX      src/service/src_libbitcoin_server_la-compat.lo
  CXX      src/service/src_libbitcoin_server_la-fetch_x.lo
  CXX      src/service/src_libbitcoin_server_la-protocol.lo
  CXX      src/service/src_libbitcoin_server_la-transaction_pool.lo
  CXX      console/console_bs-main.o
  CXXLD    src/libbitcoin-server.la
clang: warning: argument unused during compilation: '-pthread'
  CXXLD    console/bs
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "libbitcoin::set_utf8_stdio()", referenced from:
      _main in console_bs-main.o
      libbitcoin::main(int, char**) in console_bs-main.o
  "libbitcoin::cin", referenced from:
      _main in console_bs-main.o
      libbitcoin::main(int, char**) in console_bs-main.o
  "libbitcoin::cerr", referenced from:
      _main in console_bs-main.o
      libbitcoin::main(int, char**) in console_bs-main.o
  "libbitcoin::cout", referenced from:
      _main in console_bs-main.o
      libbitcoin::main(int, char**) in console_bs-main.o
  "boost::system::system_category()", referenced from:
      ___cxx_global_var_init7 in console_bs-main.o
      ___cxx_global_var_init10 in console_bs-main.o
      __GLOBAL__sub_I_main.cpp in console_bs-main.o
  "boost::system::generic_category()", referenced from:
      __GLOBAL__sub_I_main.cpp in console_bs-main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [console/bs] Error 1

**Comment by evoskuil** [comment]
@digitsu The static and dynamic OSX builds are verified in Travis, so this must be an environmental and/or configuration issue. What version of OSX are you using, and have you built on that platform successfully in the past?

**Comment by evoskuil** [comment]
The undefined libbitcoin symbols are not under conditional compilation, so they must be defined. Given that the compilation succeeds you clearly are compiling against the correct version of libbitcoin. So the only explanation that makes sense is that you are linking against a libbitcoin library that is not the one you are compiling against. This is certainly possible given libtool behavior under certain environmental conditions (e.g. environment variables affecting the build).

**Comment by thecodefactory** [comment]
@digitsu Be sure to set the PKG_CONFIG_PATH to the following, relative to the prefix *before* the install:

e.g. If prefix=/tmp/foo, do

export PKG_CONFIG_PATH=/tmp/foo/lib/pkgconfig

./install.sh --prefix=/tmp/foo ...

**Comment by digitsu** [comment]
I'm running on 10.10.5 OSX.
The only env variables I needed to add to the compilation were the ones below in order to ensure that my openssl version was the custom one.

export crypto_CFLAGS=-I/usr/local/opt/openssl/include
export crypto_LIBS=-L/usr/local/opt/openssl/lib

export bitcoin_consensus_CFLAGS=-I/usr/local/opt/openssl/include
export bitcoin_consensus_LIBS=-L/usr/local/opt/openssl/lib

export bitcoin_blockchain_CFLAGS=-I/usr/local/opt/openssl/include
export bitcoin_blockchain_LIBS=-L/usr/local/opt/openssl/lib

export bitcoin_node_CFLAGS=-I/usr/local/opt/openssl/include
export bitcoin_node_LIBS=-L/usr/local/opt/openssl/lib


Besides those, I'm using the standard install.sh as directed in the README.md
$ wget https://raw.githubusercontent.com/libbitcoin/libbitcoin-server/version2/install.sh

I will try to tinker with the prefix, though I didn't think I would have needed to as the location where it is installed should be the standard /home/myhome/dev/libbitcoin-server/build-libbitcoin-server/....
and installed to usr/local/

**Comment by digitsu** [comment]
I tried rebuilding libbitcoin with the install.sh in the master repo dir, and it builds fine.
Then I try to rebuild libbitcoin-server to see if it makes any difference.

same strange error.  What ENV vars should I be checking to make sure that its not going to the wrong libbitcoin version?  

config.status: executing libtool commands
  CXX      src/src_libbitcoin_server_la-dispatch.lo
  CXX      src/src_libbitcoin_server_la-message.lo
  CXX      src/src_libbitcoin_server_la-publisher.lo
  CXX      src/src_libbitcoin_server_la-server_node.lo
  CXX      src/src_libbitcoin_server_la-subscribe_manager.lo
  CXX      src/src_libbitcoin_server_la-worker.lo
  CXX      src/config/src_libbitcoin_server_la-config.lo
  CXX      src/config/src_libbitcoin_server_la-settings.lo
  CXX      src/service/src_libbitcoin_server_la-blockchain.lo
  CXX      src/service/src_libbitcoin_server_la-compat.lo
  CXX      src/service/src_libbitcoin_server_la-fetch_x.lo
  CXX      src/service/src_libbitcoin_server_la-protocol.lo
  CXX      src/service/src_libbitcoin_server_la-transaction_pool.lo
  CXX      console/console_bs-main.o
  CXXLD    src/libbitcoin-server.la
clang: warning: argument unused during compilation: '-pthread'
  CXXLD    console/bs
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "libbitcoin::set_utf8_stdio()", referenced from:
      _main in console_bs-main.o
      libbitcoin::main(int, char**) in console_bs-main.o
  "libbitcoin::cin", referenced from:
      _main in console_bs-main.o
      libbitcoin::main(int, char**) in console_bs-main.o
  "libbitcoin::cerr", referenced from:
      _main in console_bs-main.o
      libbitcoin::main(int, char**) in console_bs-main.o
  "libbitcoin::cout", referenced from:
      _main in console_bs-main.o
      libbitcoin::main(int, char**) in console_bs-main.o
  "boost::system::system_category()", referenced from:
      ___cxx_global_var_init7 in console_bs-main.o
      ___cxx_global_var_init10 in console_bs-main.o
      __GLOBAL__sub_I_main.cpp in console_bs-main.o
  "boost::system::generic_category()", referenced from:
      __GLOBAL__sub_I_main.cpp in console_bs-main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [console/bs] Error 1

could it be because of these envvars I added below?
configure: bitcoin_node_CPPFLAGS : -I/usr/local/opt/openssl/include
configure: bitcoin_node_LIBS : -L/usr/local/opt/openssl/lib

**Comment by digitsu** [comment]
I finally was able to get it to build clean, thanks to tinkering with the PKG_CONFIG_PATH, thanks all!

**Comment by thecodefactory** [comment]
Not sure if it applies to your case, but one common thing that's bitten me before is if you have an existing/conflicting install in the destination prefix you're trying to install into, you may see strange version conflicts like this.  To be sure, I tend to do something like this:

rm -rf $prefix
export PKG_CONFIG_PATH=$prefix/lib/pkgconfig
./install.sh --prefix=$prefix ...

**Comment by digitsu** [comment]
is it normally a good practice to install libbitcoin stuff into a custom prefix that isn't /usr/local?
I could try that, but I think it all compiles and builds now, though I can see now there might be a network issue, as I'm getting network timeouts when connecting to peers.

**Comment by digitsu** [comment]
I think due to the fact that I have mucked up my install so badly due to past attempts at building the projects (separately via ./autogen.sh ./configure, make, sudo make install, sudo ldconfig....
I'm getting really strange build incompatibilities.

most of the libraries are installed into my /usr/local now.  
is there a way to just blow them all away and start fresh?  (it would seem that even I can't do --build-boost without hitting strange errors about bzip failing to compile (part of the boost build)

**Comment by thecodefactory** [comment]
I tend to use custom other locations, at best /usr/local/mycustomdir rather than just /usr/local since often times that can cause conflicts with the distro packages (maybe not for libbitcoin, but certainly other compiled system libraries).  For libbitcoin related development and testing, I have a lot of trees around at various times, so they are all isolated to their own directories, but that's just a personal preference/convenience.  Worth trying to see if it simplifies things.

**Comment by digitsu** [comment]
Very good advice, thanks. 



—
Regards,
