### ISSUE TITLE
On Ubuntu 14.04, continuous "Failure receiving verack from [xx.xx.xx.xx] channel is stopped"

### ISSUE THREAD

**Issue by digitsu** [libbitcoin/libbitcoin-server#123]
debug.log shows a lot of timeouts...
```
22:56:39.061435 DEBUG [network] ~proxy(1)
22:56:39.061528 DEBUG [network] ~channel(1)
22:56:39.149857 DEBUG [network] ~deadline(122)
22:56:39.150057 DEBUG [network] ~connector(119)
22:56:40.173846 DEBUG [network] ~deadline(121)
22:56:40.173993 DEBUG [network] ~connector(118)
22:56:41.069925 DEBUG [network] ~deadline(120)
22:56:41.069926 DEBUG [network] ~deadline(119)
22:56:41.070236 DEBUG [network] ~connector(117)
22:56:41.070377 DEBUG [network] ~connector(116)
22:56:42.483116 DEBUG [protocol] Failure connecting [81.171.57.75:8333] connection timed out
22:56:42.483535 DEBUG [protocol] Connecting to peer [73.220.219.97:8333]
22:56:42.483868 DEBUG [network] connector(117)
22:56:42.484086 DEBUG [network] deadline(120)
22:56:43.047075 DEBUG [protocol] Failure connecting [71.94.62.199:8333] connection timed out
22:56:43.047371 DEBUG [protocol] Connecting to peer [109.157.171.134:8333]
22:56:43.047667 DEBUG [network] connector(118)
22:56:43.047838 DEBUG [network] deadline(121)
22:56:43.501874 DEBUG [network] ~deadline(120)
22:56:43.502077 DEBUG [network] ~connector(117)
22:56:43.705716 DEBUG [protocol] Failure connecting [69.172.162.113:8333] connection timed out
22:56:43.705913 DEBUG [protocol] Connecting to peer [216.144.255.51:8333]
22:56:43.706071 DEBUG [network] connector(118)
22:56:43.706155 DEBUG [network] deadline(121)
22:56:43.759636 DEBUG [protocol] Failure connecting [31.49.217.154:8333] connection timed out
22:56:43.759769 DEBUG [protocol] Connecting to peer [141.51.247.32:8333]
22:56:43.759900 DEBUG [network] connector(119)
22:56:43.759990 DEBUG [network] deadline(122)
```
stopping the server and just running bs -v give me this error
```
*** Error in `bs': double free or corruption (fasttop): 0x0000000001428040 ***
Aborted (core dumped)
```
deleting the blockchain dir and doing a bs -i gets the same error.

What could this be? (I started getting this after a new build of libbitcoin-server.  Could it be due to broken partial previous builds?

Sorry to ask so many issues.

**Comment by digitsu** [comment]
on STDOUT:

chandavid@macmini-server:~/obelisk/server$ bs
Using config file: "/usr/local/etc/libbitcoin/bs.cfg"
Please wait while server is starting.
INFO [database]: Mapping: "blockchain/blocks_lookup"
INFO [database]: Mapping: "blockchain/blocks_rows"
INFO [database]: Mapping: "blockchain/spends"
INFO [database]: Mapping: "blockchain/txs"
INFO [database]: Mapping: "blockchain/history_lookup"
INFO [database]: Mapping: "blockchain/history_rows"
INFO [database]: Mapping: "blockchain/stealth_index"
INFO [database]: Mapping: "blockchain/stealth_rows"
INFO [service]: Bound query service on tcp://*:9091
INFO [service]: Bound heartbeat service on tcp://*:9092
03:02:36.585570 INFO [node] ================= Startup =================
03:02:36.586259 ERROR [node] ================= Startup =================
03:02:36.586429 FATAL [node] ================= Startup =================
03:02:36.627259 INFO [session] Set start height (0)
03:02:36.629168 INFO [protocol] Contacting seed [seed.bitnodes.io:8333]
03:02:36.629902 INFO [protocol] Contacting seed [seed.bitcoinstats.com:8333]
03:02:36.630187 INFO [protocol] Contacting seed [seed.bitcoin.sipa.be:8333]
03:02:36.630491 INFO [protocol] Contacting seed [dnsseed.bluematt.me:8333]
03:02:36.630749 INFO [protocol] Contacting seed [seed.bitcoin.jonasschnelli.ch:8333]
03:02:36.631034 INFO [protocol] Contacting seed [dnsseed.bitcoin.dashjr.org:8333]
03:02:37.885067 INFO [protocol] Connected seed [seed.bitnodes.io:8333] as 81.162.229.164:8333
03:02:38.567496 INFO [protocol] Connected seed [seed.bitcoinstats.com:8333] as 220.245.50.171:8333
03:02:39.218326 ERROR [protocol] Failure receiving version from [81.162.229.164:8333] bad data stream
03:02:39.219100 ERROR [protocol] Failure receiving verack from [81.162.229.164:8333] channel is stopped
03:02:39.726000 INFO [protocol] Connected seed [seed.bitcoin.sipa.be:8333] as 68.235.128.200:8333
03:02:39.902994 ERROR [protocol] Failure receiving verack from [68.235.128.200:8333] channel is stopped
03:02:39.967557 ERROR [protocol] Failure receiving verack from [220.245.50.171:8333] channel is stopped
03:02:40.706428 INFO [protocol] Connected seed [dnsseed.bitcoin.dashjr.org:8333] as 24.176.8.225:8333
03:02:40.898546 ERROR [protocol] Failure receiving verack from [24.176.8.225:8333] channel is stopped
03:02:44.678710 INFO [protocol] Failure contacting seed [dnsseed.bluematt.me:8333] connection timed out
03:02:45.123300 INFO [protocol] Failure contacting seed [seed.bitcoin.jonasschnelli.ch:8333] connection timed out
03:02:45.124281 ERROR [session] Failure starting session: operation failed
03:02:45.124669 ERROR [node] Error starting session: operation failed
Node failed to start.

**Comment by evoskuil** [comment]
Master has some new incomplete work in the networking stack. I expect to be able to clear it up in the next few days. Until then you can get a good server from the top of the `version2` (release) branch.

**Comment by digitsu** [comment]
Ah... that' explains it all.  I was confusing 2 separate issues.

**Comment by evoskuil** [comment]
This is resolved, as of https://github.com/libbitcoin/libbitcoin/commit/cf19340c54bb3a59828323ba042daf38c1fecbf6.
