### ISSUE TITLE
Merkle root mismatch (ubuntu 14.04 64 bit) [master]

### ISSUE THREAD

**Issue by kobigurk** [libbitcoin/libbitcoin-server#143]
I've built libbitcoin-server from master last night, and reached block 322670 where I get merkle root mismatch and can't proceed with sync:
```
9:01:53.991925 ERROR [poller] Error storing block [00000000000000001db1c8ff51a040d517d88468148f1d07d84e4ec2fbeb1e26] from [77.72.147.193:8333] merkle root mismatch
09:01:57.173459 INFO [network] Connected to outbound channel [5.9.69.228:8333]
09:01:59.025063 ERROR [poller] Error storing block [00000000000000001db1c8ff51a040d517d88468148f1d07d84e4ec2fbeb1e26] from [5.9.69.228:8333] merkle root mismatch
09:01:59.206951 INFO [network] Connected to outbound channel [85.25.237.18:8333]
09:02:01.311739 ERROR [poller] Error storing block [00000000000000001db1c8ff51a040d517d88468148f1d07d84e4ec2fbeb1e26] from [85.25.237.18:8333] merkle root mismatch
09:02:04.284062 INFO [network] Connected to outbound channel [176.9.45.239:8333]
09:02:06.095641 ERROR [poller] Error storing block [00000000000000001db1c8ff51a040d517d88468148f1d07d84e4ec2fbeb1e26] from [176.9.45.239:8333] merkle root mismatch
09:02:06.292904 INFO [network] Connected to outbound channel [185.34.216.240:8333]
09:02:06.388919 INFO [network] Connected to outbound channel [66.206.62.226:8333]
09:02:08.469057 ERROR [poller] Error storing block [00000000000000001db1c8ff51a040d517d88468148f1d07d84e4ec2fbeb1e26] from [185.34.216.240:8333] merkle root mismatch
09:02:18.586083 INFO [network] Connected to outbound channel [106.185.33.253:8333]
```

Any ideas?
Additional info needed?

**Comment by kobigurk** [comment]
For reference, version2 goes beyond that block with no hassle.

**Comment by evoskuil** [comment]
It may be that [this issue](https://github.com/libbitcoin/libbitcoin-server/issues/134) hasn't been resolved. We may need to reopen that issue.

Master is a staging area for a future version (currently v3) , so not considered stable.

**Comment by thecodefactory** [comment]
I can reproduce this and am looking into.

**Comment by thecodefactory** [comment]
It appears that #134 is also still an issue on testnet.  Concerning -- not sure how it was resolved before on master, since at the time it was demonstrably resolved and allowed sync to progress.

**Comment by evoskuil** [comment]
I would guess they are the same issue. Master right?

**Comment by thecodefactory** [comment]
Yes, master, and they do appear to be the same.

**Comment by RojavaCrypto** [comment]
Strange. I don't have this on Ubuntu 16.04. Are the versions of the libraries different between those distros? The only possible problem I see is the ```SHA256CTX``` in ```libbitcoin/src/math/external/sha256.c``` line 98. If those libraries mismatch (a bug?) then it will fail for you with that error.

**Comment by evoskuil** [comment]
This appeared after a major refactor of the libbitcoin type library. I haven't taken time yet to track it down. But with validation not reintegrated into v3 there's presently no path to the failure.

**Comment by evoskuil** [comment]
This has been identified as a script parsing error.

**Comment by evoskuil** [comment]
This has been resolved.
