### ISSUE TITLE
Error storing block

### ISSUE THREAD

**Issue by bitcoinmarketmaker** [libbitcoin/libbitcoin-server#146]
I get the (repeating) error(s) below while using bs-linux-x64-consensus-mainnet version 2.2.0 (binary copy of BS)
```
16:47:56.131840 WARNING [validate] Failure fetching input transaction.
16:47:56.131940 WARNING [validate] Invalid input [b02ff20220431ca245b495a15306eae935b84d77b02f46b0aa587028dcc45ecf:1]
16:47:56.132058 WARNING [validate] Invalid block [000000000000000000f689874cc6cb09ca932ba373f923da9ed11263a6cc74a2] validation of inputs failed
16:47:56.132103 ERROR [poller] Error storing block [000000000000000000f689874cc6cb09ca932ba373f923da9ed11263a6cc74a2] validation of inputs failed
```

**Comment by evoskuil** [comment]
How large is your block pool?

```ini
[blockchain]
block_pool_capacity = 20
```

https://github.com/libbitcoin/libbitcoin-server/wiki/Configuration-Settings#default-settings

Also, I tagged version 2.3.0 yesterday, and will be uploading binaries for it today. This is a minor update with a couple of important fixes. It also includes an additional log message that would help in this situation.

**Comment by bitcoinmarketmaker** [comment]
I started without specifying a config file in order to get in sync.
I will try 2.3.0 when it is available and will update with additional log info.
Thank you.

**Comment by evoskuil** [comment]
Ok, I suspect you have an orphaned block at your top and are unable to clear it because of your (default) orphan pool size (1). Following initial sync you need to modify your config.

**Comment by bitcoinmarketmaker** [comment]
To me, reading from the log, the initial sync seems to stay stuck at this block. Do I have to wait or do I have to start with a specific config file now? (I already tried with the config file from https://github.com/libbitcoin/libbitcoin-server/wiki/Configuration-Settings changing the block_pool_capacity to 20)

**Comment by evoskuil** [comment]
If the issue is that you have an orphan block and a 1-sized block pool, all you would need to do is modify your configuration to increase the block pool size and restart the server. The block pool must be 1 block larger than any orphan chain that you intend to be able to overcome. Sync (under checkpoints) is optimal with a 1-sized block pool, so this is the default. If you restart with the updated config and send me a section of the log I'll look it over.

**Comment by evoskuil** [comment]
The other possibility is this: https://github.com/libbitcoin/libbitcoin-blockchain/issues/142

TL;RD - blockchain corruption (lost tx) due to hard shutdown, must be rebuilt.

**Comment by bitcoinmarketmaker** [comment]
I tried to set the block_pool_capacity  higher, no success. I did do a couple of shutdown and restarts of the server while syncing earlier today, so I think (following your message) this might have caused the problem. I will do a rebuilt now. Thank you Eric.

**Comment by evoskuil** [comment]
Shutdowns are fine as long as you use close the service out gracefully.

**Comment by evoskuil** [comment]
@bitcoinmarketmaker Any update?

**Comment by bitcoinmarketmaker** [comment]
@evoskuil I started a rebuilt after my last message and it's currently after 5 days at block 336015 and it is still catching up. The server is a intel dual-core G530, SATA2, 4GB DDR3,1000Mbps full-duplex. I think I will need to upgrade the memory to 16GB and/or use SSD to speed things up.

**Comment by evoskuil** [comment]
SSD is strongly recommended, more RAM would help (I use 8GB).

**Comment by evoskuil** [comment]
I'm going to tag this as `duplicate` of https://github.com/libbitcoin/libbitcoin-blockchain/issues/141 and close, as I'm pretty sure it's as described. Please feel free to reopen if you determine otherwise.
