### ISSUE TITLE
can't receive updates from address.subscribe

### ISSUE THREAD

**Issue by santoslluis** [libbitcoin/libbitcoin-server#147]
Hello,

I tried to do  **bx watch-address <addr>** with libbitcoin-explorer (bx) and with my own implementation in PHP against the ZMQ API, but I didn't receive any update from the server when there is a transaction.

perhaps is a bug, can anyone confirm this?

L.

**Comment by evoskuil** [comment]
There may be an issue with the server. Address subscription is not part of the network test matrix and as such a regression may evade detection. I plan to look into this shortly, as another person has reported a similar problem.

**Comment by evoskuil** [comment]
Are you running BX against your own server (BS)? Is the server configured to respond to queries (it isn't by default).

**Comment by santoslluis** [comment]
Yes, I tried with my own server, with obelisk.airbitz.co and another from the dark wallet team.

the other commands are working properly, the only that doesn't work is address.subscribe

I have the parameter 'queries_enabled' set to true.

**Comment by evoskuil** [comment]
OK, forgot to mention that you would also need to have set:
```ini
[network]
# Request that peers relay transactions, defaults to false.
relay_transactions = true
```

**Comment by santoslluis** [comment]
I've set this parameter to true and is still not working the address.subscribe command

**Comment by evoskuil** [comment]
I've made a couple of fixes and improvements to the client-server API subscription implementation in the server. I'm in the process of merging from my repo in the various affected repo version2 branches. I'll be tagging a release in the next couple of days. Thanks for reporting this issue!

**Comment by evoskuil** [comment]
Fixed in https://github.com/libbitcoin/libbitcoin-server/pull/148 and dependent repo version2 branches.

**Comment by evoskuil** [comment]
Analysis:

Transactions  that are discovered via block acceptance are not processed. This may have been a regression and was a simple fix. Block accept notifications are in addition to what may have previously been sent via mempool acceptance, so typically you should get 1 mempool notification and one block acceptance notification. Reorgs and mempool overflow with tx resend can of course cause variations.

Notification from mempool txs to be inconsistent. I believe this was a regression stemming from an incorrect virtual method override. It seems that in some builds it works as expected and in others, not at
all. I'm changing this technique from virtual handler override to mempool acceptance subscription. This will mirror the block acceptance technique (reorg subscription).

**Comment by santoslluis** [comment]
Well, I've recompiled, tested and now **address.subscribe** works fine.

Thanks!

**Comment by evoskuil** [comment]
Great, thanks for the feedback and for reporting the issue!
