### ISSUE TITLE
Request: Create binaries for Testnet 

### ISSUE THREAD

**Issue by hoffmabc** [libbitcoin/libbitcoin-server#154]
Can you guys please post binaries for the testnet build as well? That would be really convenient for us @openbazaar.

**Comment by evoskuil** [comment]
I would much rather show you how to produce a build using the `install.sh` script. I provide the binaries mostly as a demonstration.

All you need to do (Linux and OSX) is [download the installer](https://github.com/libbitcoin/libbitcoin-server/blob/version2/install.sh) and execute it. The installer downloads, configures and builds everything, and doesn't require `sudo`:
```sh
$ ./install.sh CXXFLAGS=-Os --enable-testnet --enable-ndebug --disable-shared --build-boost --prefix=/home/me/myprefix
````
We spend a lot of time making sure the builds were reliable (all build artifacts are generated source) and we test them with every commit. The build only takes a few minutes to run, less if you set `--without-tests`.

Note that version 3 will not require a `testnet` compilation distinction.

**Comment by hoffmabc** [comment]
Thank you I will try this and work off that.

**Comment by evoskuil** [comment]
@hoffmabc Great, please don't hesitate to ask if you have an issue. Odds are I've seen it. Some more info [here](https://github.com/libbitcoin/libbitcoin-server/blob/master/README.md#installation).

**Comment by evoskuil** [comment]
Also, once you have completed this static prefix build the result is the same portable binary. You can grab the one file and delete the prefix directory and the build directory with no consequence whatsoever.
