### ISSUE TITLE
Unallocated memory freed on shutdown [master]

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-server#171]
The testnet synced successfully after about 12 minutes. Let the server run about another 10 hours before issuing a CNTL-C.  The following is snippet:

08:53:15.213343 INFO [protocol] Block sync rate (0/sec) from [198.58.102.18:18333]
08:53:15.263232 INFO [protocol] Block sync rate (0/sec) from [52.10.6.141:18333]
08:53:15.290849 INFO [protocol] Block sync rate (0/sec) from [212.71.251.207:18333]
08:53:19.500205 INFO [session] Connected to block sync channel (13) [[::]]
08:53:19.538112 INFO [session] Connected to block sync channel (12) [[::]]
08:53:19.567372 INFO [session] Connected to block sync channel (10) [[::]]
08:53:19.628813 INFO [session] Connected to block sync channel (1) [[::]]
08:53:19.871759 INFO [session] Connected to block sync channel (7) [147.75.195.207:18333]
08:53:19.883951 INFO [session] Connected to block sync channel (6) [[::]]
08:53:19.961430 INFO [session] Connected to block sync channel (2) [37.59.16.106:18333]
08:53:19.990373 INFO [session] Connected to block sync channel (3) [190.16.102.214:18333]
^C08:53:24.359413 INFO [node] Please wait while server is stopping (code: 2)...
08:53:24.359524 INFO [node] Please wait while files are unmapped...
08:53:24.359664 INFO [database] Unmapping: "testnet/block_table"
08:53:24.359914 INFO [database] Unmapping: "testnet/block_index"
08:53:24.360017 INFO [database] Unmapping: "testnet/history_table"
08:53:24.360116 INFO [database] Unmapping: "testnet/history_rows"
08:53:24.360197 INFO [database] Unmapping: "testnet/spend_table"
08:53:24.360300 INFO [database] Unmapping: "testnet/stealth_index"
08:53:24.360379 INFO [database] Unmapping: "testnet/stealth_rows"
08:53:24.360458 INFO [database] Unmapping: "testnet/transaction_table"
08:53:24.368040 INFO [node] Server stopped successfully.
bs(79262,0x18604e000) malloc: *** error for object 0x7f816c805600: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by evoskuil** [comment]
Thanks, for submitting. I'll put this under the category of `won't fix` unless it's 100% reproducible. There are race conditions in version2 that won't be resolved until version3 (where they have already been resolved). It's too disruptive and time consuming to try and tackle with non-breaking changes, and two fix in two distinct branches.

**Comment by evoskuil** [comment]
Thanks for submitting. The important build id's are from network and to a lesser extent node, server isn't generally that important to this. Did you meant that testnet synced in 12 *hours*?

**Comment by evoskuil** [comment]
master [5123bce] install.sh build

**Comment by skaht** [comment]
Rebuilt **server/master** [543b885] this morning from **install.sh** commit [133233c628a77d3539853f7e08b68ae614f28541].
 
It took a little over 12 minutes to ```Synced headers 742001-743581 from [158.69.227.124:18333]```. Stopping bs immediately after a synchronization doesn't result in a core dump. Will experiment to see if CNTL-C results in any further memory issues.

Was hoping to get positive feedback for tailored bitcoin server configuration file changes for the following:

```
% bs --config bs-testnet.cfg -s

Configuration Settings:

[blockchain]
# The maximum number of orphan blocks in the pool, defaults to 50.
block_pool_capacity = <value>
# A hash:height checkpoint, multiple entries allowed.
checkpoint = <value>
checkpoint = <value>
...
# The number of threads in the blockchain threadpool, defaults to 6.
threads = <value>
# The maximum number of transactions in the pool, defaults to 2000.
transaction_pool_capacity = <value>
# Enforce consistency between the pool and the blockchain, defaults to false.
transaction_pool_consistency = <value>
# Use testnet rules for determination of work required, defaults to false.
use_testnet_rules = <value>

[database]
# The blockchain database directory, defaults to 'mainnet'.
directory = <value>
# The lower limit of spend indexing, defaults to 0.
history_start_height = <value>
# The lower limit of stealth indexing, defaults to 350000.
stealth_start_height = <value>

[network]
# IP address to disallow as a peer, multiple entries allowed.
blacklist = <value>
blacklist = <value>
...
# The maximum age limit for an outbound connection, defaults to 1440.
channel_expiration_minutes = <value>
# The maximum time limit for obtaining seed addresses, defaults to 30.
channel_germination_seconds = <value>
# The time limit to complete the connection handshake, defaults to 30.
channel_handshake_seconds = <value>
# The time between ping messages, defaults to 5.
channel_heartbeat_minutes = <value>
# The inactivity time limit for any connection, defaults to 30.
channel_inactivity_minutes = <value>
# The polling interval for initial block download, defaults to 1.
channel_poll_seconds = <value>
# The number of concurrent attempts to estalish one connection, defaults to 5.
connect_batch_size = <value>
# The time limit for connection establishment, defaults to 5.
connect_timeout_seconds = <value>
# The target number of total network connections, defaults to 16.
connection_limit = <value>
# The debug log file path, defaults to 'debug.log'.
debug_file = <value>
# The error log file path, defaults to 'error.log'.
error_file = <value>
# The maximum number of peer hosts in the pool, defaults to 1000.
host_pool_capacity = <value>
# The peer hosts cache file path, defaults to 'hosts.cache'.
hosts_file = <value>
# The magic number for message headers, defaults to 3652501241.
identifier = <value>
# The port for incoming connections, defaults to 8333.
inbound_port = <value>
# The attempt limit for manual connection establishment, defaults to 0 (forever).
manual_attempt_limit = <value>
# The target number of outgoing network connections, defaults to 8.
outbound_connections = <value>
# Request that peers relay transactions, defaults to true.
relay_transactions = <value>
# A seed node for initializing the host pool, multiple entries allowed.
seed = <value>
seed = <value>
...
# The advertised public address of this node, defaults to none.
self = <value>
self = <value>
...
# The number of threads in the network threadpool, defaults to 50.
threads = <value>

[node]
# The minimum block byte rate required from a peer during block sync, defaults to 100000.
block_bytes_per_second = <value>
# The minimum header rate required from a peer during header sync, defaults to 10000.
headers_per_second = <value>
# Persistent host:port to augment discovered hosts, multiple entries allowed.
peer = <value>
peer = <value>
...
# The number of peers to survey during sync, defaults to 1.
quorum = <value>

[server]
# The block publishing service endpoint, defaults to 'tcp://*:9093'.
block_publish_endpoint = <value>
# The path to the ZPL-encoded server private certificate file.
certificate_file = <value>
# The directory for ZPL-encoded client public certificate files, allows anonymous clients if not set.
client_certificates_path = <value>
# The heartbeat service endpoint, defaults to 'tcp://*:9092'.
heartbeat_endpoint = <value>
# The heartbeat interval, defaults to 5.
heartbeat_interval_seconds = <value>
# Write service requests to the log, defaults to false.
log_requests = <value>
# The query polling interval, defaults to 1.
polling_interval_milliseconds = <value>
# Enable the block and transaction publishing endpoints, defaults to true.
publisher_enabled = <value>
# Enable the query and heartbeat endpoints, defaults to true.
queries_enabled = <value>
# The query service endpoint, defaults to 'tcp://*:9091'.
query_endpoint = <value>
# The subscription expiration time, defaults to 10.
subscription_expiration_minutes = <value>
# The maximum number of subscriptions, defaults to 100000000.
subscription_limit = <value>
# The number of threads in the server threadpool, defaults to 2.
threads = <value>
# The transaction publishing service endpoint, defaults to 'tcp://*:9094'.
transaction_publish_endpoint = <value>
# Allowed client IP address, all clients allowed if none set, multiple entries allowed.
whitelist = <value>
whitelist = <value>
```
The following are notable deviations from the default etc/libbitcoin/bs.cfg config file for mainnet:
```
network.identifier = 118034699
network.inbound_port = 18333
network.hosts_file = hosts.cache-testnet
network.debug_file = debug-testnet.log
network.error_file = error-testnet.log
```
The network.hosts_file is written upon completion of a CNTL-C. Was important to ensure network.hosts_file file was kept segregated from that of mainnet to ensure testnet uses port 18333 instead of port 8333.

**Comment by evoskuil** [comment]
Seems fine, is there something specific you wanted me to look at?

**Comment by evoskuil** [comment]
> It took a little over 12 minutes to Synced headers 742001-743581 from [158.69.227.124:18333]

That's pretty slow. You can increase the minimum header sync rate to prevent that from happening, although that may lead to more channel churn in attempting to find a fast one. I've synced 400k headers in 15 seconds, typically 30-60s (mainnet).

**Comment by skaht** [comment]
bs crashes a few times after sync completes.  No repeatable pattern.  Sometimes on its own. Sometimes after a CNTL-C.  Rebuilding again to run overnight to see if new clues emerge.

**Comment by skaht** [comment]
Set "headers_per_second = 100000".  Header sync rate maximum is 8000/sec. Taking around ~10 minutes to sync for testnet.

**Comment by skaht** [comment]
After about 38 minutes of running testnet:

```
22:51:54.106129 INFO [session] Connected to block sync channel (13) [[::]]
22:51:54.118065 INFO [session] Connected to block sync channel (12) [[::]]
22:51:54.545441 INFO [session] Connected to block sync channel (13) [[::]]
^C22:51:54.817427 INFO [node] Please wait while server is stopping (code: 2)...
22:51:54.817539 INFO [node] Please wait while files are unmapped...
22:51:54.824960 INFO [database] Unmapping: "testnet/block_table"
22:51:54.825178 INFO [database] Unmapping: "testnet/block_index"
22:51:54.825273 INFO [database] Unmapping: "testnet/history_table"
22:51:54.825360 INFO [database] Unmapping: "testnet/history_rows"
22:51:54.825426 INFO [database] Unmapping: "testnet/spend_table"
22:51:54.825513 INFO [database] Unmapping: "testnet/stealth_index"
22:51:54.825588 INFO [database] Unmapping: "testnet/stealth_rows"
22:51:54.825772 INFO [database] Unmapping: "testnet/transaction_table"
22:51:54.826228 INFO [node] Server stopped successfully.
Segmentation fault
```

**Comment by evoskuil** [comment]
I am able to reproduce this on Linux. I'm aware of an issue where multiple connections can share what should be independent state. This is a temporary implementation, as it will be replaced with a more optimized and thread safe state manager for block sync. That should resolve this issue.

**Comment by evoskuil** [comment]
> Set "headers_per_second = 100000". Header sync rate maximum is 8000/sec. Taking around ~10 minutes to sync for testnet.

This is about 10x too high for my network. You need to set this value below your expected max, or you will keep resetting connections every 5 secs and it will take a long time to sync. It should typically take 1-2 minutes. I've seen as low as 30 secs.

**Comment by skaht** [comment]
Set the header sync rate to be a realistic 3600.  Screaming like a banchie now. Completes in under 4 minutes 45...

**Comment by evoskuil** [comment]
Closing as this appears to have been resolved.
