### ISSUE TITLE
Normal resource usage for libbitcoin-server?

### ISSUE THREAD

**Issue by hoffmabc** [libbitcoin/libbitcoin-server#178]
Does this seem like a normal resource consumption or is this crazy?

![image](https://cloud.githubusercontent.com/assets/45482/14469614/89f7bdd4-00b3-11e6-8657-d0c53fb13642.png)

**Comment by evoskuil** [comment]
> VIRT -- Virtual Memory Size (KiB). The total amount of virtual memory used by the task. It includes all code, data and shared libraries plus pages that have been swapped out and pages that have been mapped but not used.

This is primarily the blockchain swap files (on disk). The current size with full indexing is ~90GB, but there is up to 50% expansion for new writes, so 149GB is in the ball park when you add in shared libraries.

> SHR -- Shared Memory Size (KiB). The amount of shared memory available to a task, not all of which is typically resident. It simply reflects memory that could be potentially shared with other processes.

This is primarily shared libraries, mostly on disk.

> RES -- Resident Memory Size (KiB). The non-swapped physical memory a task has used.

This is primarily swap space. On my 8GB machine this is typically ~2GB, but this is up to the OS to allocate in paging the swap files. If there is more activity or more RAM available this can increase. The non-swap RAM utilization is typically on the order of 200MB.

**2148**: A spike to 79.7% CPU is not uncommon during sync.
**2141**: 168% CPU seems high - I don't know how the tool computes this.

So I don't see anything too interesting.

It is possible for memory utilization to go off the rails during sync in version2. This would happen if the one peer drops frequently, causing blocks to pile up in the work queue. In version3 there is no block queuing during sync. Instead blocks are downloaded and processed in parallel across multiple peers.

Keep in mind that the libbitcoin database is designed for high query performance. The use of a 90GB set of swap files is certainly not an optimization for RAM. You may want additional servers for redundancy, but 1 should be more than sufficient for query load.
