### ISSUE TITLE
Unable to sync headers with version 70003 node.

### ISSUE THREAD

**Issue by Sarodh** [libbitcoin/libbitcoin-server#192]
Debug.log
> 03:06:56.161272 DEBUG [protocol] Failure receiving address message from [peer:8333] channel is stopped
> 03:06:56.161295 DEBUG [protocol] Failure receiving get_address message from [peer:8333] channel is stopped
> 03:06:56.161338 DEBUG [protocol] Failure getting ping from [peer:8333] channel is stopped
> 03:06:56.161499 DEBUG [protocol] Stop protocol_version on [peer:8333] channel is stopped
> 03:06:56.161893 DEBUG [session] Header sync channel stopped: channel is stopped

Error.log
> 03:17:06.242843 WARNING [protocol] Failure merging headers from [peer:8333]
> 03:17:43.288842 WARNING [protocol] Failure merging headers from [peer:8333]

I'm using libbitcoin-server (protocol version 70001) to connect to my bitcoind node (version 70003). I initially got an error from my bitcoind server saying libbitcoin protocol version is outdated. I decided to change the minimum acceptable version to 70001 on my bitcoind node. Since then I've been receiving the above errors. If the outdated versioning is the problem is there a more recent protocol version or should I create a protocol version 70001 bitcoind node.

**Comment by evoskuil** [comment]
Hi @Sarodh, are you using a master or version2 build of `libbitcoin-server`?

**Comment by evoskuil** [comment]
Never mind, I can see from the merge failure that it's master.

**Comment by evoskuil** [comment]
The channel stopped messages are nothing more than an indication the connection was terminated. That is the expected result when there is a header merge failure on the channel. It implies the headers received from the peer either do not link to previous headers or a checkpoint has been violated.

**Comment by evoskuil** [comment]
Note that master does not yet operate as a full node. It will sync to the top checkpoint and then enable service ports, but will not maintain or supply the chain on the p2p network.

**Comment by evoskuil** [comment]
@Sarodh Do you have an update on this?

**Comment by Sarodh** [comment]
If that's the case i'll have to switch to the version2 build and see if the problem persists. Thanks.

**Comment by evoskuil** [comment]
This cannot occur in v2, since there is no headers sync. But in my experience it doesn't happen in master either. It would be good if you could confirm that your checkpoints are consistent with the node you are syncing with.

**Comment by Sarodh** [comment]
I've stopped receiving the failure merging headers log since updating my checkpoints correctly (for both versions). However, when I change libbitcoin and remake it along with all the inheriting modules, it still does not use my changes. Is there a specific process to make changes to libbitcon-server?

**Comment by evoskuil** [comment]
@Sarodh I'm not sure I understand your question. If you make changes to the sources and rebuild the changes will certainly be applied. However you cannot simply rely on the installer when acting as a maintainer (making changes to the libbitcoin sources). The installer downloads and builds from the (unchanged) repositories.

**Comment by evoskuil** [comment]
Closing as resolved by user configuration:

> I've stopped receiving the failure merging headers log since updating my checkpoints correctly
