### ISSUE TITLE
Do hosted libbitcoin-server nodes get flagged as DoS?

### ISSUE THREAD

**Issue by hoffmabc** [libbitcoin/libbitcoin-server#194]
I have two libbitcoin nodoes on two different VPS providers and both were flagged for DoS behavior. Is this a common issue? Or perhaps there's a vulnerability in the software that allow it to be used a DoS attack? Any experience with this?

**Comment by evoskuil** [comment]
I assume it's a flaw in the provider's assumptions regarding legitimate behavior. More details from the provider would be helpful.

**Comment by evoskuil** [comment]
Nobody else has reported the issue, so I assume it's not common.

**Comment by hoffmabc** [comment]
I think this was unrelated to libbitcoin we can close.
