### ISSUE TITLE
Segfault stopping server during initial block download [master]

### ISSUE THREAD

**Issue by RojavaCrypto** [libbitcoin/libbitcoin-server#195]
CTRL-C while downloading blocks (after sync) results in segmentation fault.

    19:34:57.109754 INFO [session] Channel stopped on slot (3) channel is stopped
    19:34:57.111295 INFO [database] Unmapping: "mainnet/block_table" [10534384]
    19:34:57.296938 INFO [database] Unmapping: "mainnet/block_index" [1068724]
    19:34:57.418963 INFO [database] Unmapping: "mainnet/history_table" [394971820]
    Segmentation fault (core dumped)

gdb shows `libbitcoin::from_little_endian_unsafe<unsigned int, unsigned char*> ()` with `error: Cannot access memory at address`. Stack trace shows `libbitcoin::database::history_database::add_input()` and `block_chain_impl::import()` further up.

Error is deterministically reproducible.

**Comment by evoskuil** [comment]
Yes, this is a known issue for the last couple of weeks. I haven't had a chance to track it down yet. It doesn't happen in the Windows builds, which is where I do most of my debugging, which has made it a little harder. The gdb dump is helpful.

e

**Comment by evoskuil** [comment]
Wait, you said "downloading blocks after sync". In master there is no (P2P) block download after sync (parallel initial block download). Can you confirm this is master?

**Comment by evoskuil** [comment]
Actually, I can see from the trace that it is *during* sync:
```
Channel stopped on slot (3) channel is stopped
```
There are only slots in master during sync. So this is the bug I've seen. If you complete sync it will shut down normally.

**Comment by evoskuil** [comment]
I'm getting close to completing my work to remove czmq across all repos (in addition to the removal of czmqpp and libsodium). During this I'm reworking the node/server startup/shutdown code as well. I don't think there will be an impact on the above issue, as it feels like the issue is a lapse in thread safety in the database. But once I'm done with this work I'll give it a close look.

**Comment by RojavaCrypto** [comment]
Yes, I confirm this is master. By initial sync, I meant header synchronization. If I stop in the middle of header sync, there's no error. Only when downloading initial blocks. I'll investigate further the root of this error and post info here.

**Comment by evoskuil** [comment]
I do believe that the latest changes in node/server shutdown have resolved this issue. I can no loner reproduce it. The issue was that the code was getting destroyed before all threads were closed. Please retry once #200 is merged.

**Comment by RojavaCrypto** [comment]
Sorry for the late reply- didn't have email notifications setup. Now should be working.

I am getting a crash but there is no backtrace. I'll try cleaning and rebuilding everything tomorrow then update this thread.

**Comment by evoskuil** [comment]
@RojavaCrypto Okay, thanks. It's important to update all dependent repos when updating any single repo, as there are frequent changes across the libraries. Simply executing the `install.sh` is the easiest way to do this. This is how I execute *all* of my linux and osx builds. It takes a little longer than incremental build, but it guarantees consistency on the initial build. After that incremental builds are of course fine. When using `$ install.sh --prefix <dir>` the entire build is isolated to the directory and does not require `sudo`.

**Comment by RojavaCrypto** [comment]
OK, thanks for the useful tip. I'm on this now.

**Comment by RojavaCrypto** [comment]
I just cleaned my repos, then used the install script to rebuild everything. Running the server then stopping during block download gives:

`Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000XXX in ?? ()
[Current thread is 1 (LWP XXXXXX)]
(gdb) bt
#0  0x0000XXX in ?? ()
#1  0x0000XXX in ?? ()
#2  0x0000XXX in ?? ()
#3  0x0000XXX in ?? ()
#4  0x0000XXX in ?? ()
#5  0x0000000000000000 in ?? ()
`

Which is the same as before using the install.sh script. Anyway I'm going to clear everything (including blockchain download) and try again to see if I can reproduce it.

**Comment by RojavaCrypto** [comment]
OK, just done the rebuild, started a new chain. Seems to work fine. Will keep trying a few times at later blocks to see if problem reproduces, otherwise I'll close this ticket.

**Comment by RojavaCrypto** [comment]
I spoke too soon. Original error still exists.

    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0xXXXX in libbitcoin::from_little_endian_unsafe<unsigned long, unsigned char*> (in=0xXXXX <error: Cannot access memory at address 0xXXX>)
        at /home/foo/usr/include/bitcoin/bitcoin/impl/utility/endian.ipp:72
    72	        out |= static_cast<T>(*in++) << (8 * i++);
    [Current thread is 1 (Thread 0xXXX (LWP XXX))]
    (gdb) bt
    #0  0xXXXX in libbitcoin::from_little_endian_unsafe<unsigned long, unsigned char*> (in=0xXXX <error: Cannot access memory at address 0xXXXX>)
        at /home/foo/usr/include/bitcoin/bitcoin/impl/utility/endian.ipp:72
    #1  libbitcoin::database::hash_table_header<unsigned int, unsigned long>::read (
        this=<optimized out>, index=61912)
        at ./include/bitcoin/database/impl/hash_table_header.ipp:110
    #2  0xXXXX in libbitcoin::database::slab_hash_table<std::array<unsigned char, 32ul> >::read_bucket_value (this=this@entry=0xXXXX, key=...)
        at ./include/bitcoin/database/impl/slab_hash_table.ipp:138
    #3  0xXXXXX in libbitcoin::database::slab_hash_table<std::array<unsigned char, 32ul> >::store(std::array<unsigned char, 32ul> const&, std::function<void (std::shared_ptr<libbitcoin::database::memory>)>, unsigned long) (this=this@entry=0xXXX, key=..., 
        write=..., value_size=value_size@entry=7288)
        at ./include/bitcoin/database/impl/slab_hash_table.ipp:43
    #4  0x0XXXXX in libbitcoin::database::block_database::store (
        this=this@entry=0xXXXX, block=..., height=height@entry=133883)
        at src/databases/block_database.cpp:131
    #5  0xXXXX in libbitcoin::database::data_base::push (
        this=this@entry=0xXXXX, block=..., height=height@entry=133883)
        at src/data_base.cpp:306
    #6  0xXXXXX in libbitcoin::blockchain::block_chain_impl::import (
        this=0xXXXX, block=std::shared_ptr (count 6, weak 0) 0xXXXX, height=133883)
        at src/block_chain_impl.cpp:246
    #7  0xXXXXX in libbitcoin::node::reservations::import (this=<optimized out>, 
        block=std::shared_ptr (count 6, weak 0) 0xXXXX, height=<optimized out>)
        at src/utility/reservations.cpp:56
    #8  0xXXXX in libbitcoin::node::reservation::<lambda()>::operator() (
        __closure=<synthetic pointer>) at src/utility/reservation.cpp:340
    #9  libbitcoin::timer<std::chrono::duration<long, std::ratio<1l, 1000000l> >, std::chrono::_V2::system_clock>::duration<libbitcoin::node::reservation::import(libbitcoin::chain::block::ptr)::<lambda()> > (func=...)
        at /home/foo/usr/include/bitcoin/bitcoin/utility/timer.hpp:57
    #10 libbitcoin::node::reservation::import (this=0xXXXXX, 
        block=std::shared_ptr (count 6, weak 0) 0xXXXX)
        at src/utility/reservation.cpp:344
    #11 0xXXXXX in libbitcoin::node::protocol_block_sync::handle_receive(std::error_code const&, std::shared_ptr<libbitcoin::chain::block>, std::function<void (std::error_code const&)>) (this=0xXXXXXX, ec=..., 
        message=std::shared_ptr (count 6, weak 0) 0xXXXXX, complete=...)
        at src/protocols/protocol_block_sync.cpp:130

**Comment by evoskuil** [comment]
> Anyway I'm going to clear everything (including blockchain download) and try again to see if I can reproduce it.

If you experience a hard (uncontrolled) shutdown of the database you must assume the store is corrupt and must delete it before restarting. Also, if you do not complete an initial block download, there are gaps in the chain that cannot be repaired by restarting (although this feature is coming). So you must either complete the initial block download or restart it with a new chain. Though it should stop cleanly at any time.

**Comment by evoskuil** [comment]
The stack trace shows normal operation of the database after node receipt of a block during initial block download. Threads must be joined before the database is stopped. I would assume from the segfault that the database has been stopped before threads are joined. I can see in the code how this is happening. 

The design is that `stop` of each repo is non-blocking and signals termination, and `close` is blocking. There is a problem in the database-blockchain shutdown in that the database stop is unmapping the files, but this is being called from the blockchain stop, which is supposed to be signal only. The database stop needs to be called from a blockchain close, and the blockchain (and database) close needs to be blocking. I'll fix this up today.

**Comment by RojavaCrypto** [comment]
OK, when the blocking `stop()` is committed let me know here and I'll test again.

**Comment by evoskuil** [comment]
I've just completed this work. I'll be checking it in later today.

**Comment by evoskuil** [comment]
I decided to refine a couple of aspects of this, should be merging soon.

**Comment by evoskuil** [comment]
@RojavaCrypto This should be resolved, please try it out - thanks!

**Comment by RojavaCrypto** [comment]
OK will do now. Is there a command to update and build all repos?

**Comment by evoskuil** [comment]
Just delete the build and prefix directories and re-execute the install.sh.

**Comment by RojavaCrypto** [comment]
Fixed. Tried on different computers, was able to stop, start with no segmentation fault.
