### ISSUE TITLE
Transaction and block publishers not started [version2]

### ISSUE THREAD

**Issue by Sarodh** [libbitcoin/libbitcoin-server#198]
```
INFO [service]: Bound query service on tcp://*:9091
INFO [service]: Bound heartbeat service on tcp://*:9092
```
None of the publisher.cpp code is invoked, despite enabling it in bs.cfg

**Comment by evoskuil** [comment]
Assuming this is in `version2` and not in `master` (since the `publisher` class does not exist in `master`) - do you have `server.publisher_enabled = true` set?

**Comment by Sarodh** [comment]
> # Enable the block and transaction publishing endpoints, defaults to false.
> publisher_enabled = true
> # Enable the query and heartbeat endpoints, defaults to false.
> queries_enabled = true

Yes I do, and I am using version2

**Comment by evoskuil** [comment]
Can you post the full startup console trace and debug log?

**Comment by Sarodh** [comment]
Console
> Using config file: "/usr/local/etc/libbitcoin/bs.cfg"
> Please wait while server is starting.
> INFO [database]: Mapping: "blockchain/blocks_lookup"
> INFO [database]: Mapping: "blockchain/blocks_rows"
> INFO [database]: Mapping: "blockchain/spends"
> INFO [database]: Mapping: "blockchain/txs"
> INFO [database]: Mapping: "blockchain/history_lookup"
> INFO [database]: Mapping: "blockchain/history_rows"
> INFO [database]: Mapping: "blockchain/stealth_index"
> INFO [database]: Mapping: "blockchain/stealth_rows"
> INFO [service]: Bound query service on tcp://*:9091
> INFO [service]: Bound heartbeat service on tcp://*:9092
> 19:41:02.314086 INFO [node] ================= Startup =================
> 19:41:02.314508 ERROR [node] ================= Startup =================
> 19:41:02.314539 FATAL [node] ================= Startup =================
> 19:41:02.314987 INFO [session] Set start height (5399)
> Server started, press CTRL-C to stop.

Debug.log
19:46:19.725437 DEBUG [node] ================= Startup =================
19:46:19.725568 INFO [node] ================= Startup =================
19:46:19.726031 INFO [session] Set start height (5399)
19:46:25.727447 DEBUG [protocol] Connecting to peer [myothernode]
19:46:25.727799 DEBUG [blockchain] Stopping transaction pool: service is stopped

**Comment by evoskuil** [comment]
The only way I can see this as possible is in the case where the publisher is not enabled in this file: usr/local/etc/libbitcoin/bs.cfg

If the value is set then the debug log or stdout/stderr will always emit either a success or failure message.

**Comment by Sarodh** [comment]
The tx port doesn't broadcast raw transactions? Is that not implemented yet?

**Comment by evoskuil** [comment]
It is implemented and should be functional in version2. My comment above is just that it must be enabled. The only case I can find where it would not log success or failure at startup is if it is not enabled in the configuration file that is in use.

**Comment by Sarodh** [comment]
@evoskuil  Hey, I've been using the publisher endpoints successfully. I've noticed that the tx endpoint seems to disconnect after a while, the block endpoint however does not.

**Comment by evoskuil** [comment]
Hi @Sarodh, thanks for the feedback. Please check the logs for messages as indicated here: https://github.com/libbitcoin/libbitcoin-server/blob/version2/src/publisher.cpp
