### ISSUE TITLE
Process terminated on x64 OSX 10.10 (Yosemite)

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#20]
Build: bfda2fa28cd5da9a0b34600c83d01496f1af46fa
```
  Model Name:	iMac
  Model Identifier:	iMac8,1
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	6 MB
  Memory:	4 GB
  Bus Speed:	1.07 GHz
  Boot ROM Version:	IM81.00C1.B00
  SMC Version (system):	1.29f1
```
Sync was completed through:
```
INFO [poller]: Block #158199 0000000000000e716e6593afab209ed612f8a74b7fc014adee935ecaca46018e
```
Console message:
```
Bus error: 10
```
Contact me for logs.

**Comment by genjix** [comment]
did you run out of disk space?

**Comment by evoskuil** [comment]
No, it's a 400GB drive with 327GB free.

**Comment by genjix** [comment]
did it leave a core file behind?

**Comment by evoskuil** [comment]
No, I'll have to rerun it with the core dump facility turned on. Note that this is built with clang.

**Comment by evoskuil** [comment]
While I"m working on that, I can suggest a place to look at the source.

The failure is similar in Windows and OSX, in that the process was terminated after a lengthy execution where a similar number of blocks were sync'd. There is a section of port code that only affects Windows (see mman-win32) but another section that affects *both* Windows and OSX but not linux:

```c++
bool mmfile::resize(size_t new_size)
{
    // Resize underlying file.
    if (ftruncate(file_handle_, new_size) == -1)
        return false;

    // Readjust memory map.

    // OSX mman and mman-win32 do not implement mremap or MREMAP_MAYMOVE.
    // This may not be most efficient but it is a simple resolution.
#ifndef MREMAP_MAYMOVE
    if (munmap(data_, size_) == -1)
        return false;

    data_ = static_cast<uint8_t*>(mmap(
        0, new_size, PROT_READ | PROT_WRITE, MAP_SHARED, file_handle_, 0));
#else
    data_ = static_cast<uint8_t*>(mremap(
        data_, size_, new_size, MREMAP_MAYMOVE));
#endif

    if (data_ == MAP_FAILED)
        return false;

    size_ = new_size;
    return true;
}
```

**Comment by evoskuil** [comment]
Additional info: restarting the server (with the same data files) results in the server continuing to sync as prior to the failure. I've enabled core dump and am waiting for recurrence.

**Comment by evoskuil** [comment]
Failed again, core dump uploading.

**Comment by evoskuil** [comment]
This error was resolved by an integer overflow patch to the mmfile implementation.
