### ISSUE TITLE
Add tx radar to query endpoint.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#222]
Implement in manner of address/prefix subscription. Capture subscription in a radar subscriber and normalize relay of new transaction and block messages as transaction id's with heights, to the subscribers. Terminate the subscription based on timeout, 100% completion or height that indicates block acceptance.

Capture the number of peers and subscriber metadata into the radar subscription. Subscription to responses must be made against inventory message tx hashes, not to mempool acceptance.

Capture of the count accumulator will require a counter object allocated as a shared pointer. This will allow increment without the need to recreate the closure (which would otherwise preclude resubscription). As the subscription closure owns the accumulator it will be destroyed at non-resubscription, but it will remain modifiable in each execution of the closure. [This technique can also be used to provide a sequence to all query subscription notifications, allowing the caller to detect dropped notifications.]

At timeout, detection of the tx in a block, or 100% response, notify the subscriber that no subsequent notifications will be issued. Integrate the 'renew' message used for address/prefix subscription, allowing the caller to extend an existing registration against timeout.

**Comment by evoskuil** [comment]
See initial stub here: https://github.com/evoskuil/libbitcoin-server/blob/master/src/workers/notification_worker.cpp#L37-L76

```cpp
// TX RADAR
// By monitoring for tx inventory we do not poll and therefore will not
// suffer from peers that don't provide redundant responses, will not
// suffer double-counting, or have complexity and poor perf from caching.
// However this requires that the user subscribe *before* submitting a
// transaction. This feature is useful for the submitter of the tx to the
// network - generally the spender. This is intended to allow the spender
// to increase fees (ie using replace by fee). It is *not* recommended for
// use by a receiver (ie for the acceptance of zero confirmation txs).
```

**Comment by evoskuil** [comment]
This requires that the server incorporate broadcaster functionality natively. Transactions must be broadcast to one set of peers and received from another set. These sets must be independent and we must take care not to forward an original txt between the two sets. This would also simplify deployment, since one server (and an identically configured fallback) becomes sufficient. But this is more work than allowed for tax radar in the 3.0 release, so I'm deferring txt radar to a later update.

**Comment by RojavaCrypto** [comment]
Normal usage is broadcast(tx) and then server gives updates showing propagation throughout the network: notify(0.1), notify(0.2), ... notify(1.0) - where the value is calculated as the ratio of hosts that replied / total_connections.

**Comment by evoskuil** [comment]
The issue here is that a node cannot both broadcast a tx to its peers and monitor those same peers for penetration. This would suffer from two problems: (1) some peers may not reflect back the transaction (a problem in the existing implementation, since our own mempool may never see it), and (2) some peers may reflect back every received tx even if not accepted into the peer's mempool (which would give us no indication of actual penetration).

**Comment by RojavaCrypto** [comment]
It's not difficult. We have a separate group of hosts that's only ever used for monitoring the transactions.

https://github.com/darkwallet/txradar/blob/master/txradar.hpp

Probably better is the reverse though. bc::network::protocol only for broadcasting (6 hosts for example), and another bc::network::protocol (main set of hosts) used for everything else including monitoring sent transactions (100 hosts for example).

**Comment by evoskuil** [comment]
Yes, that's basically what I'm thinking.
