### ISSUE TITLE
Wire protocol compatibility breaks.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#23]
As of f34b4ac61cc20f9f15e30b2c33773998faac7147 the following BX calls have compatibility breaks against `libbitcoin-server` in relation to the `obelisk/version1` protocol.

* fetch-balance
* fetch-history
* fetch-stealth
* watch-address

The cause of the `fetch-balance` break is not yet known.

The `fetch-history` break is the result of an intended API change may be resolved by subsequent commit bb657e3281e55c02a013bf93daa0f25f563889cd which splits out the new feature into a distinct call. Testing is underway.

The `fetch-stealth` and `watch-address` breaks are known to be the result of protocol changes. It may be OK to break `fetch-stealth` as it has been experimental and use is likely limited. However we may want to consider compatibility for `watch-address`. The cause of the breaks is a sentinel in the protocol to allow for the detection of a stealth prefix vs. a bitcoin address.

**Comment by swansontec** [comment]
AirBitz doesn't use fetch-stealth, so this API is fine to break (stealth isn't standardized yet anyhow).

**Comment by evoskuil** [comment]
What about address subscribe (watch-address)?

**Comment by swansontec** [comment]
AirBitz is not using subscribe. I don't know what the OpenBazaar guys are using, but it might be worth getting in contact with them.

**Comment by hoffmabc** [comment]
We are not using watch-address at this time.

**Comment by evoskuil** [comment]
Thanks

**Comment by evoskuil** [comment]
Closed the wrong issue.

**Comment by genjix** [comment]
is fetch-balance still broken? Maybe the balance of the addresses changed?

**Comment by evoskuil** [comment]
I haven't been able to retest with latest, since the sync is still ongoing (slower than last time).

But the problem was not due to a change in balance.

**Comment by evoskuil** [comment]
If I run the following command:
```sh
$ bx fetch-history 134HfD2fdeBTohfx8YANxEpsYXsv5UoWyz
```
against `tcp://obelisk.airbitz.co:9091` the following results:
```js
transfers
{
    transfer
    {
        received
        {
            hash 97e06e49dfdd26c5a904670971ccf4c7fe7d9da53cb379bf9b442fc9427080b3
            height 247683
            index 1
        }
        spent
        {
            hash b7354b8b9cc9a856aedaa349cffa289ae9917771f4e06b2386636b3c073df1b5
            height 247742
            index 0
        }
        value 100000
    }
}
```
but running the same command against `libbitcoin-server` returns:
```js
transfers ""
``` 
which is the indication that should result if no rows are returned. Other addresses yield the same results, correct data from Obelisk servers and an empty result from `libbitcoin-server`.

Note that this is not the most recent build (that is still syncing) but I don't believe anything was updated in `fetch-history` so this should be current.

**Comment by genjix** [comment]
How do I configure the server in bx?

BTW if you change this setting: history_db_active_height = 0 in the server.cfg, it means the height at which to start indexing history. If you've set that then you may not have all the history rows if some history for an address begins before the history_db_active_height.

Make sure your blockchain is up to date:

$ cd PATH/blockchain/
$ block_db last_height blocks_lookup blocks_rows 
339062

And make sure the history is correct (it work fine for me):

$ history_db fetch history_lookup history_rows 134HfD2fdeBTohfx8YANxEpsYXsv5UoWyz
SPEND:  b7354b8b9cc9a856aedaa349cffa289ae9917771f4e06b2386636b3c073df1b5:0 247742 1964747877775310849
OUTPUT: 97e06e49dfdd26c5a904670971ccf4c7fe7d9da53cb379bf9b442fc9427080b3:1 247683 100000

**Comment by genjix** [comment]
I just got bx fetch-history working and see the same result as Eric. Seems to be a change in the wire format as it exists in the database fine.

**Comment by genjix** [comment]
Ok, see #195. bx is using blockchain.fetch_history when it should be using address.fetch_history.

$ bx fetch-history 134HfD2fdeBTohfx8YANxEpsYXsv5UoWyz --config ~/.bx.cfg 
transfers
{
    transfer
    {
        received
        {
            hash 97e06e49dfdd26c5a904670971ccf4c7fe7d9da53cb379bf9b442fc9427080b3
            height 247683
            index 1
        }
        spent
        {
            hash b7354b8b9cc9a856aedaa349cffa289ae9917771f4e06b2386636b3c073df1b5
            height 247742
            index 0
        }
        value 100000
    }
}
$ bx fetch-balance 134HfD2fdeBTohfx8YANxEpsYXsv5UoWyz --config ~/.bx.cfg 
balance
{
    address 134HfD2fdeBTohfx8YANxEpsYXsv5UoWyz
    confirmed 0
    received 100000
    unspent 0
}

**Comment by pmienk** [comment]
@genjix could you point me in the direction of where I could find or explain the difference between address.fetch_history and blockchain.fetch_history?  Should blockchain.fetch_history be removed from the client?  I don't see it documented [here](https://libbitcoin.dyne.org/obelisk/api.html#blockchain), but it's present in the obelisk v1 codebase, does this indicate a 'private' method for test?

**Comment by genjix** [comment]
Simply put blockchain.fetch_history calls fetch_history for the blockchain. address.fetch_history calls blockchain.fetch_history and on the transaction pool also (so you get unconfirmed transactions). See here: https://github.com/libbitcoin/libbitcoin-node/blob/master/include/bitcoin/node/transaction_indexer.hpp#L137

**Comment by evoskuil** [comment]
@genjix Assuming it tests out against Obelisk we can make the change to BX to use `address.fetch_history` but since there's a break to the public API `blockchain.fetch_history` we should also confirm with AirBitz and OpenBazaar.

@swansontec and @hoffmabc would a change to `blockchain.fetch_history` break your apps?

**Comment by evoskuil** [comment]
fetch-balance and fetch-history are now resolved and confirmed as compatible with obelisk, watch-address and fetch-stealth are not compatible but we have accepted the break.
