### ISSUE TITLE
send-tx-node returns "Service stopped"

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#24]
This is a BX test case that is failing against `libbitcoin-server` but not `obelisk\version1`.
```sh
$ bx send-tx-node
0100000001b3807042c92f449bbf79b33ca59d7dfec7f4cc71096704a9c526dddf496ee0970100000069463044022039a36013301597daef41fbe593a02cc513d0b55527ec2df1050e2e8ff49c85c202204fcc407ce9b6f719ee7d009aeb8d8d21423f400a5b871394ca32e00c26b348dd2103c40cbd64c9c608df2c9730f49b0888c4db1c436e8b2b74aead6c6afbd10428c0ffffffff01905f0100000000001976a91418c0bd8d1818f1bf99cb1df2269c645318ef7b7388ac00000000
```
Each time the above call is executed (on ubuntu) where `libbitcoin-server` is running locally, the server emits the following console messages:
```
22:48:26.540978 INFO [protocol]: Accepted connection: 2
22:48:26.541496 ERROR [protocol]: Problem receiving addresses: Service stopped
22:48:26.541539 ERROR [session]: inventory: Service stopped
22:48:26.541547 ERROR [poller]: Received bad inventory: Service stopped
22:48:26.541571 ERROR [session]: get_blocks: Service stopped
22:48:26.541604 ERROR: recv_transaction: Service stopped
22:48:26.541632 ERROR [poller]: Received bad block: Service stopped
22:48:26.541662 ERROR [protocol]: Channel stopped (inbound): Service stopped
22:48:26.541690 ERROR [protocol]: Sending error: Service stopped
```
and the BX command returns:
```
Service stopped
```

**Comment by genjix** [comment]
The command is trying to send to a localhost node (if you don't pass a HOST / PORT on the command line). Are you running a bitcoin daemon on localhost?

**Comment by evoskuil** [comment]
Yes, libbitcoin-server.

**Comment by evoskuil** [comment]
Notice also in the description above that `libbitcoin-server` logs a specific pattern of messages to the console each time that this command is executed.

**Comment by evoskuil** [comment]
This appears to be an improperly represented but otherwise correct error. When transmitting a previously-mined tx to a server, success is the initial response. But sending it a second time to the same server yields this result. However after some amount of time the issue will clear and repeat if reattempted.

**Comment by evoskuil** [comment]
Logging has been updated with greater granularity so this should be reviewed again.
