### ISSUE TITLE
Error: unrecognised option 'network.relay_transactions'

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-server#327]
Did a fresh build with default heads.  Title above results from executing new **bs** executable using either **bs --initchain** or just **bs**.  Could not find "relay_transactions" in the configuration file under [network].
```
% bs -v
```
```
Version Information:

libbitcoin-server:     4.0.0
libbitcoin-protocol:   4.0.0
libbitcoin-node:       4.0.0
libbitcoin-blockchain: 4.0.0
libbitcoin:            4.0.0
```

**Comment by evoskuil** [comment]
There is no such option supported but you have it in your config file. The config option for relay_transactions is under node. I recommend reconstructing your config file from the current version that ships with the source.

**Comment by skaht** [comment]
Don't know what I did, but apparently I did not copy and tweak the right file...  

My Mac is still freezing up at block 3400, then block 7400...  Behaviors appear to be unchanged from a couple of weeks back. Any configuration suggestions?

**Comment by evoskuil** [comment]
If you are getting delays every 2000 blocks, just reduce the block polling interval. If you are seeing a deadlock it's an[ open issue](https://github.com/libbitcoin/libbitcoin-blockchain/issues/332) as of a couple days ago. It can be reduced by reducing the peer count and increasing the network thread count.
