### ISSUE TITLE
The fetch-stealth call should only return tx hash.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#37]
Otherwise the caller must always follow-up with requests for all transactions, which is very wasteful.

**Comment by RojavaCrypto** [comment]
It's better this way though, because otherwise the server might have to send a huge block of transactions. This way the client receives the hashes then gradually downloads the transactions.

**Comment by evoskuil** [comment]
Without a way to privately recover the transactions, this problem defeats a primary benefit of stealth. However the same basic issue currently exists for non-stealth payments to standard addresses (i.e. using privately-passed HD wallet addresses). The resolution to this will ultimately be to support PIR queries. However a stealth response of a set of tx hashes followed by a PIR query for transactions is going to suffer from an intersection attack, so I'm not sure how else to resolve the central privacy issue with this.

**Comment by RojavaCrypto** [comment]
Sorry, what's PIR queries? Any link? Thanks.

**Comment by evoskuil** [comment]
https://en.m.wikipedia.org/wiki/Private_information_retrieval

**Comment by evoskuil** [comment]
The "gradually" term in your previous comment is an attempt to break a timing attack. I wouldn't consider this effective or particularly friendly from a usage standpoint. If one has control of the user's network or the server this is easily defeated. Using encryption on the wire the network arrack is hard, but the public server based attack remains trivial.

**Comment by RojavaCrypto** [comment]
I think it's more a way to stave off resource starvation. Imagine starting a new wallet that you want to synchronize for the first time. The wallet can put the stealth synchronization to a background thread at a low priority allowing it to be usable. It's not desirable to immediately download all transaction data immediately. With the hashes + fetching, you essentially have a resumable download and you can calculate the progress.

**Comment by RojavaCrypto** [comment]
Thanks for the link on PIR. I don't know how stealth has changed, but before it was based on inexact prefix matching that would return false positive transactions. So the idea there was that you'd also fetch transactions that weren't for you. You could increase or decrease this with the number of bits in the prefix. Not sure if that helps.

**Comment by evoskuil** [comment]
Nothing in stealth has changed since the initial (v2) release apart from the completion of a couple of aspects. The PIR objective of blockchain-based stealth transaction discovery would only be satisfied if client download all transactions signaled by the filtered query.

I think that given the options this is best because it allows the client to throttle the response. In version4 all responses will support pagination, so this specialization would not be necessary.

However, the current implementation is hazardous because it encourages unsafe usage. We are returning sufficient stealth metadata to the client for the client to detect the specific transaction(s) of interest. This is *only* useful in the case where the client does *not* intend to download the full set of transactions.

So I would be fine with client pulling the transactions, but in this case we should eliminate the stealth metadata from the initial response as it constitutes dead code. In doing so we can also eliminate server indexing of both the ephemeral public key hash and the stealth public key hash. We would only send the transaction hashes that satisfy the indexed filter.

**Comment by RojavaCrypto** [comment]
Interesting problem. I think this implies that stealth addresses should have a timelimit on them. Otherwise you have a stealth address with an unlimited number of transactions in its prefix that you have to read forever. If there was a limit, then you would re-issue the address with a stronger or weaker prefix.

However the key hashes, are so you can tell which rows are valid, then it's up to the client to mix in some invalid transaction hashes. I was confused before but that's the basic idea for anonymizing transactions. When you multiply the keys, only the client can see which addresses belong to it.

**Comment by evoskuil** [comment]
> However the key hashes, are so you can tell which rows are valid, then it's up to the client to mix in some invalid transaction hashes.

The key hashes are in the transactions, so indexing them and returning them in the query result is unnecessary and encourages unsafe use.

> When you multiply the keys, only the client can see which addresses belong to it.

Sure, but again, this should be done at the client - since the client must download the transactions anyway.

> If there was a limit, then you would re-issue the address with a stronger or weaker prefix.

Time in Bitcoin is measured in blocks. The amount of clock time passed has no affect on the query results, only change in the change does that. So the minimum height parameter of the query is sufficient for controlling for excess

**Comment by RojavaCrypto** [comment]
There is no need to return the key hashes if, and only if, the client will download *all* of the transactions for that prefix search.

But does the client want to download all of the transactions necessarily? Maybe the client decides to compromise anonymity by downloading less transactions that it does not need.

Wrt time measured in blocks. Sure, but when a user decides to create an expiring stealth address, the client software will suggest an expiry time. Rather like a PGP key, other clients will refuse to send to an expire stealth address. The whole point of an expiry time is that you don't have a prefix that forever accepts payments and becomes stuffed with transactions that you cannot stop. If they have an expiry, then at some point you re-issue a new stealth address (which can be signed by the old one), and yes, it is also additional security to stop them being compromised.

It does not need to be based on the blockchain, because the client could simply find the block issued at that time and query stealth up to that block index. However neither way makes a big difference.

Maybe worth asking Peter about this.

**Comment by evoskuil** [comment]
> There is no need to return the key hashes if, and only if, the client will download all of the transactions for that prefix search.

Of course, but the set is presumably limited in block height (and by prefix selection). And by providing the hashes the client hash throttling ability, the lack of which was the original concern raised above.

> Maybe the client decides to compromise anonymity by downloading less transactions that it does not need.

This is my concern. It seems likely that clients will either download only the matching transactions, or will use a selection criteria that defeats the benefit of the remaining anonymity set. Not only does the client need to request a set when there is a match, the client should select a set when there are no matches. The client is the creator of the stealth address so it would seem that this should be managed by the selection of the prefix. If the prefix becomes too expensive within a single block (which seems unlikely) it would need to be discarded.

WRT expiry time, this is an issue that affects all public payment addresses. But in general I think that payment channels are likely to supersede widespread adoption of stealth. This is a point that PT raised when we were discussing the stealth BIP.

**Comment by evoskuil** [comment]
`protocol.fetch_stealth` is deprecated in v3
```
    // response
    // [ code:4 ]
    // [[ ephemeral_key_hash:32 ][ address_hash:20 ][ tx_hash:32 ]...]
```

`protocol.fetch_stealth2` is new in v3
```
    // response
    // [ code:4 ]
    // [[ tx_hash:32 ]...]
```

**Comment by evoskuil** [comment]
Resolved in: #236

**Comment by RojavaCrypto** [comment]
Old scheme:

1. fetch_stealth
2. Iterate returned hashes, find address, fetch transactions + some random transactions

New scheme:

1. fetch_stealth
2. If transaction set is too large, fetch_stealth again but with a larger prefix
3. Fetch all transactions once tx hash set reaches an acceptable size.

**Comment by evoskuil** [comment]
Yes, reduction of the anonymity set is possible, increase would be ill-advised. This makes safe implementation much simpler, though a bit more parsing on the client.

**Comment by RojavaCrypto** [comment]
The newer scheme can be more unsafe. For every new bit in the prefix, we roughly half the results returned. Client has to fetch and fetch but then crosses the boundary.

Also it means multiple queries to the server repeatedly with increasing prefix sizes.

**Comment by evoskuil** [comment]
I am not advocating for the New Scheme scenario as described. My comments above are only to caution one against any attempt to *increase* the anonymity set by the same identifiable client (depending on how "same client" may be identified by the server... e.g. IP address, Tor channel, secure channel).

Height should be used to manage the average size of the anonymity set. The result set is bounded by the max stealth txs per block times the number of blocks queried. If one gets way behind and the result set gets large it can certainly be costly to recover.

In the Old Scheme described above, generally querying at previously-queried heights allows the attacker to easily exclude the overlap from the anonymity set. So in that scenario height must be used not for managing performance but as an essential privacy measure. It is also essential that the *size* of the follow-on query set vary unpredictably and be applied even when there are no matches.

IMO the Old Scheme should not be used for polling (i.e. working at the top of the chain), although it may be necessary in the case of recovery after a long offline period.

**Comment by evoskuil** [comment]
Following up on my own comment above: "If one gets way behind and the result set gets large it can certainly be costly to recover." This is really the relevant scenario. **You should fully understand the consequences of using the Old Scheme in any case.**

It is very likely that you **entirely defeat** the anonymity afforded by prefix filtering if you do not query the entire result set from the server after each `fetch-stealth` call. Any single result that you do not include provides an exclusion bit for intersection analysis. There is no way to exclude entries and preserve anonymity. An attacker will generally be able to recover the **specific transactions of interest** to the client.

You have a choice between performance and privacy. If you can't afford the performance hit you should simply query in the clear. Otherwise you are promoting a false sense of privacy.

I should also point out that posting a transaction without using an anonymizing network (e.g. Tor, I2P) compromises the addresses in the transaction (by associating them with the caller's IP address). If these transactions are payments to or from stealth addresses those stealth addresses are also compromised. So stealth should never be used without secure transaction submission, and its benefits are directly defeated.
