### ISSUE TITLE
I need some help for the initial settings of the configuration

### ISSUE THREAD

**Issue by jjmr007** [libbitcoin/libbitcoin-server#399]
I'm a newbie in these coding issues, so any help is very appreciated. 
I want to try on my pc this bitcoin server software, but I don´t know if I set the configuration properly.
I'm using windows 7.
I just download the bs.cfg from [the raw data](https://raw.githubusercontent.com/libbitcoin/libbitcoin-server/version3/data/bs.cfg) as a .txt file (bs.cfg.txt). 

Then I created the directory:  C:\ProgramData\libbitcoin then I put there the file, and manually erased the .txt extension.

But when I run in the command line `>bs -s` I got back a data list in which each parameter seems to lack any setting. They just indicate "`<value>`".  [This is the output I got.](https://github.com/libbitcoin/libbitcoin-server/files/1006555/settings.txt)

Then I run `>bs --initchain` and try to start the server, [obtaining this outcome](https://github.com/libbitcoin/libbitcoin-server/files/1006562/start.fails.txt).

What may I be doing wrong? thanks!

**Comment by evoskuil** [comment]
The `-s` option only shows the settings that are available, not the current values. When the server starts up it indicates the path to the config file in use.

**Comment by evoskuil** [comment]
This error indicates that less than 100 seed addresses were obtained from seed nodes.
```
03:53:08.750174 ERROR [network] Error seeding host addresses: unresponsive peer may be throttling
```
Delete the `hosts.cache` and try again.

**Comment by thecodefactory** [comment]
I've seen this error on occasion also.  Simply the restarting the server gets it going as well.

**Comment by jjmr007** [comment]
Thank you!
I deleted the entire line holding the word `hosts.cache` and ran bs. It's syncing smoothly so far!

**Comment by evoskuil** [comment]
Restarting without deleting the small hosts.cache can work, but it usually results in an inability to find any good host.

**Comment by jjmr007** [comment]
Just an ending comment:

I'm still syncing my libbitcoin server. (And it is fine) But meanwhile I tried to perform some fetch commands on bitcoin explorer, and I alway got the error message: `connection timed out`

I thought that could be related to the fact that the server isn't synced yet. But then I tried deleting the whole configuration line containing `hosts.cache` in the bx.cfg file as well, and now they're running fine!
(Even with the bs.exe stopped!)

**Comment by evoskuil** [comment]
bx is configured with a default mainnet server, so you are running queries against it by default:
```ini
[server]
url = tcp://mainnet.libbitcoin.net:9091
```
See [bx server settings](https://github.com/libbitcoin/libbitcoin-explorer/wiki/Server-Settings)

bs must be running and at least have its query endpoint enabled:
```ini
[server]
query_workers = 1
```
See [bs server settings](https://github.com/libbitcoin/libbitcoin-server/wiki/Server-Settings)
