### ISSUE TITLE
Version reporting without access to sources

### ISSUE THREAD

**Issue by veox** [libbitcoin/libbitcoin-server#4]
It can be difficult to determine which exact version of the server is running. If it was downloaded using `git`, then `git describe` can be used. However, if a stable version is used (think Obelisk ATM), there's no way to find out for non-priviledged users that don't have access to sources.

This complicates bug reporting, including cases where a "git HEAD" archive was used for deployment.

I suggest either a `-V` command-line argument be introduced, or the info be printed at lauch time. Minimal versioning info is available in `configure.ac` ATM.

**Comment by evoskuil** [comment]
Implemented as:
```sh
$ bitcoin_server --version
```
```
testnet: false
libbitcoin: 2.8.0
libbitcoin-server: 2.0.0
```

**Comment by evoskuil** [comment]
Pending push of commit: https://github.com/evoskuil/libbitcoin-server/commit/e9db0a22511068412009a2532967d45251db9a9f
