### ISSUE TITLE
Status of regtest support.

### ISSUE THREAD

**Issue by sundance30203** [libbitcoin/libbitcoin-server#404]
I am trying to use libbitcoin and libbitcoin-server in a regtest network, and am having trouble connecting libbitcoin-server to an established regtest network of bitcoind instances (versions 0.12.0 and 0.14.2).

I've explored two approaches: 
1) Create a regtest network with libbitcoin-server instances only, or
2) Connect libbitcoin-server to a bitcoind regtest network I already have tested.

Given, regtest support is not yet exposed to the user in libbitcoin (see #https://github.com/libbitcoin/libbitcoin/issues/697 and #https://github.com/libbitcoin/libbitcoin-node/issues/280), option 1 does not appear to be available right now, and I have been attempting option 2 unsuccessfully for a few days.

Any help for a workaround until full regtest support is released (be it a config, or a code hack) will greatly be appreciated. libbitcoin otherwise seems to be exactly what I am looking for.

In my attempts at option 2, instead of observing the hoped-for behavior of libbitcoin-server synching the regtest blocks to its database, the process fails and loops in the channel-establishment phase. Below is the output observed:

```
11:18:15.107270 INFO [server] ================= startup  ==================
11:18:15.107419 WARNING [server] ================= startup  ==================
11:18:15.107459 ERROR [server] ================= startup  ==================
11:18:15.107468 FATAL [server] ================= startup  ==================
11:18:15.107475 INFO [server] Using config file: "bs.cfg"
11:18:15.107488 INFO [server] Please wait while the server is starting...
11:18:15.108034 INFO [network] Starting manual session.
11:18:15.108091 INFO [network] Not configured to populate an address pool.
11:18:15.108110 INFO [server] Seeding is complete.
11:18:15.108131 INFO [node] Node start height is (0).
11:18:15.108200 INFO [network] Not configured for accepting incoming connections.
11:18:15.108220 INFO [network] Starting outbound session.
11:18:15.108243 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108327 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108355 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108379 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108400 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108442 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108454 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108462 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108470 WARNING [network] Failure fetching new address: object does not exist
11:18:15.108528 WARNING [network] Failure fetching new address: object does not exist
11:18:15.111124 INFO [server] Bound public query service to tcp://*:9091
11:18:15.111696 INFO [server] Bound public heartbeat service to tcp://*:9092
11:18:15.111935 INFO [server] Bound public block service to tcp://*:9093
11:18:15.112116 INFO [server] Bound public transaction service to tcp://*:9094
11:18:15.112156 INFO [server] Server is started.
11:18:15.172250 INFO [network] Manual channel failed to start [127.0.0.1:17593] channel stopped
11:18:15.187202 INFO [network] Manual channel failed to start [<ip redacted>:17591] channel stopped
11:18:15.190013 INFO [network] Manual channel failed to start [<ip redacted>:17592] channel stopped
11:18:15.194386 INFO [network] Manual channel failed to start [<ip redacted>:17594] channel stopped
11:18:15.195832 INFO [network] Manual channel failed to start [<ip redacted>:17595] channel stopped
11:18:15.224187 INFO [network] Manual channel failed to start [127.0.0.1:17593] channel stopped
11:18:15.262703 INFO [network] Manual channel failed to start [<ip redacted>:17591] channel stopped
11:18:15.265603 INFO [network] Manual channel failed to start [<ip redacted>:17592] channel stopped
11:18:15.270978 INFO [network] Manual channel failed to start [<ip redacted>:17594] channel stopped
11:18:15.277505 INFO [network] Manual channel failed to start [<ip redacted>:17595] channel stopped
11:18:15.278238 INFO [network] Manual channel failed to start [127.0.0.1:17593] channel stopped

```
and so on...

On the bitcoind side, I observe this repeated message

```
2017-08-16 11:18:15 Added connection peer=1
2017-08-16 11:18:15 connection from 127.0.0.1:41102 accepted
2017-08-16 11:18:15 PROCESSMESSAGE: INVALID MESSAGESTART version peer=1
2017-08-16 11:18:15 disconnecting peer=1
2017-08-16 11:18:15 Cleared nodestate for peer=1

```

Clearly, the MESSAGESTART version is problematic. I presume this refers to the magic message header as configured in bs.cfg. In my config, I get the same outcome regardless of whether I use the mainnet or testnet magic numbers. Is there a different number for regtest? Even if so, would libbitcoin handle it transparently?

Another possibly unrelated problem seems to be related to the fact that regtest uses no seed hosts while testnet and mainnet do and libbitcoin-server does not expose a configuration option for regtest so that it doesn't look for a seed host.

For libbitcoin, I run these versions:
Version Information:
libbitcoin-server:     3.3.0
libbitcoin-protocol:   3.1.0
libbitcoin-node:       3.3.0
libbitcoin-blockchain: 3.3.0
libbitcoin:            4.0.0

(Not sure why libbitcoin is 4.0.0, this is what I get when I build both from the install script and manually even though I'm on the version 3 branch for all repos.)

My regtest network consists of five remote bitcoind 0.12.0 full nodes and one local bitcoind 0.14.2 all interconnected. libbitcoin-server is connected to all through the following configuration. I list my bitcoind nodes as persistent peers, commented out all seed hosts, and set the maximum number of peer hosts to zero (otherwise the default mainnet or testnet seeds will be used).

```
[network]
# The minimum number of threads in the network threadpool, defaults to 0 (physical
 cores).
threads = 0
# The maximum network protocol version, defaults to 70013.
protocol_maximum = 70013
# The minimum network protocol version, defaults to 31402.
protocol_minimum = 31402
# The services exposed by network connections, defaults to 1 (full node).
services = 1
# The advertised services that cause a peer to be dropped, defaults to 0 (none).
invalid_services = 0
# The magic number for message headers, defaults to 3652501241 (use 118034699 for testnet).
identifier = 118034699
#identifier = 3652501241
# Validate the checksum of network messages, defaults to false.
validate_checksum = false
# The port for incoming connections, defaults to 8333 (use 18333 for testnet).
inbound_port = 18333
#inbound_port = 8333
# The target number of incoming network connections, defaults to 0.
inbound_connections = 0
# The target number of outgoing network connections, defaults to 2.
outbound_connections = 2
# The attempt limit for manual connection establishment, defaults to 0 (forever).
manual_attempt_limit = 0
# The number of concurrent attempts to establish one connection, defaults to 5.
connect_batch_size = 5
# The time limit for connection establishment, defaults to 5.
connect_timeout_seconds = 5
# The time limit to complete the connection handshake, defaults to 30.
channel_handshake_seconds = 30
# The time between ping messages, defaults to 5.
channel_heartbeat_minutes = 5
# The inactivity time limit for any connection, defaults to 30.
channel_inactivity_minutes = 30
# The age limit for any connection, defaults to 60.
channel_expiration_minutes = 60
# The time limit for obtaining seed addresses, defaults to 30.
channel_germination_seconds = 30
# The maximum number of peer hosts in the pool, defaults to 1000.
host_pool_capacity = 0
# The peer hosts cache file path, defaults to 'hosts.cache'.
hosts_file = hosts.cache
# The advertised public address of this node, defaults to none.
self = 0.0.0.0:0
# IP address to disallow as a peer, multiple entries allowed.
#blacklist = 127.0.0.1
# A persistent peer node, multiple entries allowed.
peer = <my remote server>:17591
peer = <my remote server>:17592
peer = 127.0.0.1:17593
peer = <my remote server>:17594
peer = <my remote server>:17595
#peer = testnet.libbitcoin.net:8333
# A seed node for initializing the host pool, multiple entries allowed, defaults shown.
#seed = 0.0.0.0:0
#seed = seed.bitcoin.sipa.be:8333
#seed = dnsseed.bluematt.me:8333
#seed = dnsseed.bitcoin.dashjr.org:8333
#seed = seed.bitcoinstats.com:8333
#seed = seed.bitcoin.jonasschnelli.ch:8333
#seed = seed.voskuil.org:8333
# Testnet seed nodes.
#seed = testnet-seed.bitcoin.jonasschnelli.ch:18333
#seed = seed.tbtc.petertodd.org:18333
#seed = testnet-seed.bluematt.me:18333
#seed = testnet-seed.bitcoin.schildbach.de:18333
#seed = testnet-seed.voskuil.org:18333

```

Thanks in advanced!

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin-server/wiki/Frequently-Asked-Questions#q-is-regtest-supported

**Comment by sundance30203** [comment]
Eric, understood that regtest is not supported yet. 

To clarify, my question is rather about a) whether it is possible for me to get connected to my regtest network with minor changes in config and/or code, and b) whether you might have some hints as to what I could do to at least resolve the above. For example, am I on the right path by thinking the disconnect is related to the network magic header?

I'm willing to tinker with the libs for my prototype and will continue to do so for as long is reasonable. I'm trying to avoid the route of coding RPC calls directly to bitcoind in C++ when all this wonderful functionality is available in libbitcoin. I'm new to libbitcoin (not new to C++ or bitcoin); any insights into the steps to get something minimally functional on regtest will be appreciated.

I'm looking to establish blockchain sync, basic block/transaction query functionality, and to relay transactions that I create with libbitcoin for a prototype application I'm building.

**Comment by sundance30203** [comment]
When I use the regtest network magic number (identifier = 3669344250) in bs.cfg, I get connected to bitcoind regtest, so that was that small issue.

Not surprisingly, a disconnect happens about 60 seconds later with the below message from bitcoind.

At this point, I'm guessing that as libbitcoin seemed to recognize the networks by the config indentifier, the new indentifier does not have a corresponding definition internally (genesis block hash, version bits, etc). This might cause the connection to be dropped during the initial blockchain sync (particularly the genesis block hash).  
```
2017-08-17 02:13:59 Added connection peer=651
2017-08-17 02:13:59 connection from 127.0.0.1:44800 accepted
2017-08-17 02:13:59 received: version (104 bytes) peer=651
2017-08-17 02:13:59 sending version (103 bytes) peer=651
2017-08-17 02:13:59 send version message: version 70015, blocks=0, us=[::]:0, peer=651
2017-08-17 02:13:59 sending verack (0 bytes) peer=651
2017-08-17 02:13:59 receive version message: /libbitcoin:4.0.0/: version 70013, blocks=0, us=127.0.0.1:17593, peer=651
2017-08-17 02:13:59 received: verack (0 bytes) peer=651
2017-08-17 02:13:59 sending sendheaders (0 bytes) peer=651
2017-08-17 02:13:59 sending ping (8 bytes) peer=651
2017-08-17 02:13:59 sending feefilter (8 bytes) peer=651
2017-08-17 02:13:59 received: ping (8 bytes) peer=651
2017-08-17 02:13:59 sending pong (8 bytes) peer=651
2017-08-17 02:13:59 received: sendheaders (0 bytes) peer=651
2017-08-17 02:13:59 received: getheaders (69 bytes) peer=651
2017-08-17 02:13:59 Ignoring getheaders from peer=651 because node is in initial block download
2017-08-17 02:13:59 received: feefilter (8 bytes) peer=651
2017-08-17 02:13:59 received: feefilter of 0.00000189 BTC/kB from peer=651
2017-08-17 02:13:59 received: pong (8 bytes) peer=651
2017-08-17 02:14:59 socket closed
2017-08-17 02:14:59 disconnecting peer=651
2017-08-17 02:14:59 Cleared nodestate for peer=651

```
I'll look into the libbitcoin usage of the mainnet and testnet definitions and see if it is related to the blockchain sync process. 

Alas, still getting the warnings about failure to fetch network addresses in libbitcoin-server. I'm guessing I might need to take these more seriously to progress.
```
02:19:52.582497 INFO [server] ================= startup  ==================
02:19:52.582596 WARNING [server] ================= startup  ==================
02:19:52.582673 ERROR [server] ================= startup  ==================
02:19:52.582687 FATAL [server] ================= startup  ==================
02:19:52.582702 INFO [server] Using config file: "bs.cfg"
02:19:52.582716 INFO [server] Please wait while the server is starting...
02:19:52.583409 INFO [network] Starting manual session.
02:19:52.583511 INFO [network] Not configured to populate an address pool.
02:19:52.583569 INFO [server] Seeding is complete.
02:19:52.583623 INFO [node] Node start height is (0).
02:19:52.583693 INFO [network] Not configured for accepting incoming connections.
02:19:52.583708 INFO [network] Starting outbound session.
02:19:52.583757 WARNING [network] Failure fetching new address: object does not exist
02:19:52.584914 WARNING [network] Failure fetching new address: object does not exist
02:19:52.584926 WARNING [network] Failure fetching new address: object does not exist
02:19:52.584934 WARNING [network] Failure fetching new address: object does not exist
02:19:52.584942 WARNING [network] Failure fetching new address: object does not exist
02:19:52.585463 INFO [server] Bound public query service to tcp://*:9091
02:19:52.588618 INFO [network] Connected manual channel [127.0.0.1:17593] as [127.0.0.1:17593] (1)
02:19:52.589491 INFO [server] Bound public heartbeat service to tcp://*:9092
02:19:52.589724 INFO [server] Bound public block service to tcp://*:9093
02:19:52.589985 INFO [server] Bound public transaction service to tcp://*:9094
02:19:52.590094 INFO [server] Server is started.
02:19:57.586297 WARNING [network] Failure fetching new address: object does not exist
02:19:57.586460 WARNING [network] Failure fetching new address: object does not exist
02:19:57.586500 WARNING [network] Failure fetching new address: object does not exist
02:19:57.586537 WARNING [network] Failure fetching new address: object does not exist
02:19:57.586569 WARNING [network] Failure fetching new address: object does not exist
02:20:02.589979 WARNING [network] Failure fetching new address: object does not exist
02:20:02.590109 WARNING [network] Failure fetching new address: object does not exist
02:20:02.590146 WARNING [network] Failure fetching new address: object does not exist
02:20:02.590177 WARNING [network] Failure fetching new address: object does not exist
02:20:02.590208 WARNING [network] Failure fetching new address: object does not exist
02:20:07.591508 WARNING [network] Failure fetching new address: object does not exist
02:20:07.591634 WARNING [network] Failure fetching new address: object does not exist
```

**Comment by evoskuil** [comment]
```
02:19:52.583708 INFO [network] Starting outbound session.
...
02:19:52.583511 INFO [network] Not configured to populate an address pool.
```

This means you will have no addresses from which to select outbound peers. Check your [config](https://github.com/libbitcoin/libbitcoin-server/wiki/Network-Settings),
 should be this by default:
```ini
[network]
# The maximum number of peer hosts in the pool, defaults to 1000.
host_pool_capacity = 1000
```

**Comment by evoskuil** [comment]
This is correct for setting magic (assuming the value is the correct):
```
[network]
identifier = 3669344250
```

**Comment by evoskuil** [comment]
I'm not a bitcoind user, but this error implies that bitcoind will reject `getheaders` requests until it has completed syncing its own chain:
```
2017-08-17 02:13:59 Ignoring getheaders from peer=651 because node is in initial block download
```
FWIW, libbitcoin does not have this limit. It will honor requests during its own sync as long as it is able.

**Comment by evoskuil** [comment]
I'm assuming you will at least need to update the [genesis block](https://github.com/libbitcoin/libbitcoin/blob/version3/src/chain/block.cpp#L58-L96),  some [constants](https://github.com/libbitcoin/libbitcoin/blob/version3/include/bitcoin/bitcoin/constants.hpp) and probably [work required computation](https://github.com/libbitcoin/libbitcoin/blob/version3/src/chain/chain_state.cpp#L316-L417) (as is the case with testnet).

**Comment by sundance30203** [comment]
Excellent, thanks for pointing me to those files.

That is a good clue; once that node's block download is completed, bitcoind might honor the getheaders request, and perhaps that might allow libbitcoin-server to complete its.

**Comment by evoskuil** [comment]
Please feel free to ask any other questions. It will be good to have the required changes documented, or even a feature branch off of `version3` in the necessary repos.

**Comment by evoskuil** [comment]
Prob need to fix genesis and init first.

**Comment by sundance30203** [comment]
Absolutely, if something good comes of this, I will be sure to share here or in a feature branch.

**Comment by sundance30203** [comment]
hardcoding additional values and logic for regtest appears to work. will modify and test bx as well

**Comment by sundance30203** [comment]
bx works as well after configuring bx.cfg with the regtest identifier, setting testnet params for the other settings, and removing the seed peers. So with bs, I have blocks synced, and bx queries transactions from my regtest network seemlessly. I'll have better confirmation after creating my prototype app.

**Comment by quiquee** [comment]
@sundance30203 thanks for the work on this. 
Before I start setting my own server for regtest. Is there any chance this was documented or it will be added to a feature branch ?
Thank you !

**Comment by sundance30203** [comment]
I'd be happy to share the mods I did. I've been testing them with a prototype app that I built since last updating this log, and so far it has worked fine, with the exception of one issue that's not a blocker for me. Because I am new to libbitcoin, I doubt the mods are yet fit for the purpose of a feature branch, but I am glad to share the diffs here.

**Comment by quiquee** [comment]
That would be great , many thanks

**Comment by evoskuil** [comment]
@sundance30203 I would really like to see this as well, as it would greatly facilitate full integration. No need for an implementation branch.

**Comment by lastcanal** [comment]
I've implemented regtest network support and it's working great for me! I've indexed over 12000 regtest blocks with bs. You can see the code in these pull requests: https://github.com/libbitcoin/libbitcoin/pull/838 and https://github.com/libbitcoin/libbitcoin-server/pull/415

It requires building libbitcoin with the `WITH_REGTEST` flag defined. The only other option (that i can see) is to pass the currently configured network identifier all the way down to every function that uses `proof_of_work_limit`. 

I have not updated any makefiles, but a `--with-regtest` flag defining `WITH_REGTEST` is all that would be needed to make this functional. The flag would only need to be defined when building libbitcoin

I've tested connecting to regtest enabled bitcoind v0.15.1 and v0.14.2 without issue.

**Comment by evoskuil** [comment]
See: https://github.com/libbitcoin/libbitcoin/pull/841

**Comment by evoskuil** [comment]
Regtest is now implemented in full, please give feedback!

**Comment by lastcanal** [comment]
The 'retarget' config setting is working great!! It connects to the regtest network on bitcoind v0.15.1 and v0.14.2 with only a few extra bs config changes.

It turns out bip34 activation is [pushed far into the future on regtest](https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp#L276), so `bip34` must be set to false in the config.

Here is a diff between my working regtest config and the default config:

```diff
< identifier = 3652501241
---
> identifier = 3669344250
43c43
< outbound_connections = 2
---
> outbound_connections = 0
61c61
< host_pool_capacity = 1000
---
> host_pool_capacity = 0
70a71
> peer = 127.0.0.1:18333
72,77c73,78
< seed = seed.bitcoin.sipa.be:8333
< seed = dnsseed.bluematt.me:8333
< seed = dnsseed.bitcoin.dashjr.org:8333
< seed = seed.bitcoinstats.com:8333
< seed = seed.bitcoin.jonasschnelli.ch:8333
< seed = seed.voskuil.org:8333
---
> #seed = seed.bitcoin.sipa.be:8333
> #seed = dnsseed.bluematt.me:8333
> #seed = dnsseed.bitcoin.dashjr.org:8333
> #seed = seed.bitcoinstats.com:8333
> #seed = seed.bitcoin.jonasschnelli.ch:8333
> #seed = seed.voskuil.org:8333
113,130c114,131
< checkpoint = 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f:0
< checkpoint = 0000000069e244f73d78e8fd29ba2fd2ed618bd6fa2ee92559f542fdb26e7c1d:11111
< checkpoint = 000000002dd5588a74784eaa7ab0507a18ad16a236e7b1ce69f00d7ddfb5d0a6:33333
< checkpoint = 00000000001e1b4903550a0b96e9a9405c8a95f387162e4944e8d9fbe501cd6a:68555
< checkpoint = 00000000006a49b14bcf27462068f1264c961f11fa2e0eddd2be0791e1d4124a:70567
< checkpoint = 0000000000573993a3c9e41ce34471c079dcf5f52a0e824a81e7f953b8661a20:74000
< checkpoint = 00000000000291ce28027faea320c8d2b054b2e0fe44a773f3eefb151d6bdc97:105000
< checkpoint = 000000000000774a7f8a7a12dc906ddb9e17e75d684f15e00f8767f9e8f36553:118000
< checkpoint = 00000000000005b12ffd4cd315cd34ffd4a594f430ac814c91184a0d42d2b0fe:134444
< checkpoint = 000000000000033b512028abb90e1626d8b346fd0ed598ac0a3c371138dce2bd:140700
< checkpoint = 000000000000099e61ea72015e79632f216fe6cb33d7899acb35b75c8303b763:168000
< checkpoint = 000000000000059f452a5f7340de6682a977387c17010ff6e6c3bd83ca8b1317:193000
< checkpoint = 000000000000048b95347e83192f69cf0366076336c639f9b7228e9ba171342e:210000
< checkpoint = 00000000000001b4f4b433e81ee46494af945cf96014816a4e2370f11b23df4e:216116
< checkpoint = 00000000000001c108384350f74090433e7fcf79a606b8e797f065b130575932:225430
< checkpoint = 000000000000003887df1f29024b06fc2200b55f8af8f35453d7be294df2d214:250000
< checkpoint = 0000000000000001ae8c72a0b0c301f67e3afca10e819efa9041e458e9bd7e40:279000
< checkpoint = 00000000000000004d9b4ef50f0f9d686fd69db2e03af35a100370c64632a983:295000
---
> #checkpoint = 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f:0
> #checkpoint = 0000000069e244f73d78e8fd29ba2fd2ed618bd6fa2ee92559f542fdb26e7c1d:11111
> #checkpoint = 000000002dd5588a74784eaa7ab0507a18ad16a236e7b1ce69f00d7ddfb5d0a6:33333
> #checkpoint = 00000000001e1b4903550a0b96e9a9405c8a95f387162e4944e8d9fbe501cd6a:68555
> #checkpoint = 00000000006a49b14bcf27462068f1264c961f11fa2e0eddd2be0791e1d4124a:70567
> #checkpoint = 0000000000573993a3c9e41ce34471c079dcf5f52a0e824a81e7f953b8661a20:74000
> #checkpoint = 00000000000291ce28027faea320c8d2b054b2e0fe44a773f3eefb151d6bdc97:105000
> #checkpoint = 000000000000774a7f8a7a12dc906ddb9e17e75d684f15e00f8767f9e8f36553:118000
> #checkpoint = 00000000000005b12ffd4cd315cd34ffd4a594f430ac814c91184a0d42d2b0fe:134444
> #checkpoint = 000000000000033b512028abb90e1626d8b346fd0ed598ac0a3c371138dce2bd:140700
> #checkpoint = 000000000000099e61ea72015e79632f216fe6cb33d7899acb35b75c8303b763:168000
> #checkpoint = 000000000000059f452a5f7340de6682a977387c17010ff6e6c3bd83ca8b1317:193000
> #checkpoint = 000000000000048b95347e83192f69cf0366076336c639f9b7228e9ba171342e:210000
> #checkpoint = 00000000000001b4f4b433e81ee46494af945cf96014816a4e2370f11b23df4e:216116
> #checkpoint = 00000000000001c108384350f74090433e7fcf79a606b8e797f065b130575932:225430
> #checkpoint = 000000000000003887df1f29024b06fc2200b55f8af8f35453d7be294df2d214:250000
> #checkpoint = 0000000000000001ae8c72a0b0c301f67e3afca10e819efa9041e458e9bd7e40:279000
> #checkpoint = 00000000000000004d9b4ef50f0f9d686fd69db2e03af35a100370c64632a983:295000
138a140,141
> # Regtest Checkpoints
> checkpoint = 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206:0
144c147
< retarget = true
---
> retarget = false
150c153
< bip34 = true
---
> bip34 = false
```

**Comment by evoskuil** [comment]
Thanks for the quick feedback @lastcanal. I am not yet quite sure what is intended by the delayed bip34 activation, since bip90 requires bip34 activation (and requires a hash for its first block).

**Comment by evoskuil** [comment]
This does not match the port number for the default regtest configuration, are you sure this is correct?
```
peer = 127.0.0.1:18333
```

**Comment by evoskuil** [comment]
I haven't added anything to the config comments for regtest, but good call on the genesis block to prevent the others:
```
checkpoint = 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206:0
```

**Comment by lastcanal** [comment]
You are correct my config had the wrong peer config, the default regtest port is `18444`.

    peer = 127.0.0.1:18444

BIP34 seems to be deactivated because of v1 block tests in bitcoin core. There are a couple more forks that are deactivated on the default regtest network.

 Here are the pertinent sections of `getblockchaininfo` as of block 13100:

```json
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": false
      }
    }, 
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    }, 
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 0,
      "timeout": 999999999999,
      "since": 432
    },
    "segwit": {
      "status": "active",
      "startTime": 0,
      "timeout": 999999999999,
      "since": 432
    }
  }
```

It looks like the bitcoin core RPC tests do something special to activate BIP65 and BIP66. Maybe something similar can be done to activate BIP34 at some height below block 100000000.

```cpp
consensus.BIP34Height = 100000000; // BIP34 has not activated on regtest (far in the future so block v1 are not rejected in tests)
consensus.BIP34Hash = uint256();
consensus.BIP65Height = 1351; // BIP65 activated on regtest (Used in rpc activation tests)
consensus.BIP66Height = 1251; // BIP66 activated on regtest (Used in rpc activation tests)
```

**Comment by evoskuil** [comment]
I'm pretty sure they are relying on the bip90 hardwired height activation for bip65/66, which should apply equally to bip34, apart from any restrictions they've placed on it for legacy testing.

```cpp
// Regtest (arbitrary) frozen activation heights (frozen_activations).
BC_CONSTEXPR size_t regtest_bip65_freeze = 1351;
BC_CONSTEXPR size_t regtest_bip66_freeze = 1251;
BC_CONSTEXPR size_t regtest_bip34_freeze = 0;
```

The need for the bip34 checkpoint (as opposed to just a height) is the result of the `allow collisions` hard-fork/hack. Since they have future (never) activation for bip34, it implies that bip30 remains active at all heights.

The csv/segwit activation windows allow for computation of activation based on history, but those bips specify particular (different) dates. Libbitcoin doesn't bother to implement bip9 because these time windows are closed and cannot be reactivated, making bip9 dead code at this point. We activated these based on a checkpoint for mainnet and testnet. But since there aren't checkpoints for anything but genesis on testnet, this technique cannot be used. So I've activated csv with a genesis checkpoint, and will do the same for segwit.

**Comment by evoskuil** [comment]
See config topic: https://github.com/libbitcoin/libbitcoin-server/wiki/Regtest-Configuration

**Comment by lastcanal** [comment]
Thanks Eric! The arbitrary activation values for regtest make more sense to me now. It looks like regtest activates segwit at genesis too, so I think what you are doing makes sense. This is a great addition to libbitcoin! I can't wait to start using it in development!! :)

**Comment by evoskuil** [comment]
Thanks for kicking it off. It always helps to have someone using a feature to get it done right. The csv/segwit forks are *activated* at height 432 in Core, assuming all blocks signal starting at block 0 (or 1?). We can't easily activate there because it requires `bip9`.

**Comment by lastcanal** [comment]
Ah, yes, the _signaling_ for csv/segwit starts at block 1 in Core. I really don't see any harm in activating csv/segwit at genesis on regtest, especially if it would require `bip9` to do otherwise. I will let you know if it causes any issues for me going forward.

**Comment by tabbyreyez** [comment]
Hey @sundance30203 , I am doing a personal project involving the Bitcoin network. I have setup a local Bitcoin test environment which is working correctly - it is definitely not connected to the global Bitcoin network. I am trying to use libbitcoin to automate behaviour within this test environment, however I am struggling massively to use libbitcoin-client to connect to one of my nodes in the test environment. In order for my Bitcoin nodes to see one another, I am adding an "addnode=<ANOTHER NODE IP ADDRESS>" entry into my config file and running via ./

From your first comment it sounds like you were able to connect your libbitcoin-server to your Bitcoin nodes. Can you please help me out with configuring a similar set up to yours? I have spent almost 2 weeks trying to figure this out and failing miserably. 

P.s. I am very new to the world of Bitcoin, and my aims are to solely play around with my test environment for personal research (i.e. I have no aim to start trading Bitcoin properly) and understand how to use libbitcoin
