### ISSUE TITLE
What is the statsd implementation status?

### ISSUE THREAD

**Issue by garceri** [libbitcoin/libbitcoin-server#406]
I'd like to know what's the status on the statsd sink implementation.

**Comment by pmienk** [comment]
I believe there's a working initialization routine in the [libbitcoin](https://github.com/libbitcoin/libbitcoin/blob/master/include/bitcoin/bitcoin/log/statsd_sink.hpp#L33) repository.  However the initialization is not invoked in any derivative project, nor is there any instrumentation for metrics.  The mechanism for reporting events has been defined in the [source file](https://github.com/libbitcoin/libbitcoin/blob/master/include/bitcoin/bitcoin/log/statsd_source.hpp), providing macros for reporting counter, gauge and timer events with or without rate.  As it's been awhile, I can't remember if some of that cross product isn't supported by implementations, but I believe by my interpretation at the time of implementation they were all valid.

I don't know that instrumentation is currently a priority, but it should be as simple as invoking the appropriate macro with a name `string` and data with the understanding that counters are `int64_t`, gauges are `uint64_t`, timers are `asio::milliseconds` and rates are `float` data types.

**Comment by evoskuil** [comment]
@garceri Can we be of any further assistance?

**Comment by evoskuil** [comment]
Closing as complete.
