### ISSUE TITLE
Set up as server for DarkWallet

### ISSUE THREAD

**Issue by dabura667** [libbitcoin/libbitcoin-server#425]
Just to be clear, if I run `bs` with default settings on mainnet and it syncs, will I just be able to set my server's IP in DarkWallet (latest alpha) and connect to it as an obelisk server, or is there some settings I need to pass on to it when syncing/running?

**Comment by evoskuil** [comment]
I'm not familiar with the status of DW, but in the last discussion I understood that the v3 server API was aligned. Default configuration (assuming mainnet) should be fine in that case.

**Comment by dabura667** [comment]
I noticed bs process is not listening on the websocket port though...

hmmm

**Comment by evoskuil** [comment]
BS is not a websocket server. DarkWallet implements its own proxy for that.

**Comment by dabura667** [comment]
ok I was confused because DW client says wss:// for the default server, and when I put in an IP it keeps saying “disconnexted from wss://x.x.x.x:9735”

So the websocket is to something locally run by the client and it connects to bs via rpc or something?

Thanks

**Comment by evoskuil** [comment]
I think it's actually a server component.

**Comment by dabura667** [comment]
Hmmm... for the time being I have a while until I’m done syncing.

I’ll look into the websocket server component.

Any idea where it might be?

**Comment by dabura667** [comment]
https://github.com/darkwallet/gateway

Think I found it.

It says it needs zmq and obelisk.

Those active out of the box with default settings?

**Comment by evoskuil** [comment]
Yes, it's just the client-server protocol.
