### ISSUE TITLE
libzmq >= 4.2.3 required

### ISSUE THREAD

**Issue by streamofstars** [libbitcoin/libbitcoin-server#439]
Ubuntu Server 16.04 LTS 

Upon installing all dependencies listed [here](https://github.com/libbitcoin/libbitcoin-server) and running install.sh I am getting an error claiming libzmq >= 4.2.3 is required.

First of all, please add a mechanism to check such dependencies at script startup. Install.sh runs for like 15 minutes compiling and whatnot and only then suddenly complains about missing libs. Waste of time.

Secondly, please list libzmq on the above linked website along with installation steps (be aware, required version at this moment is not present in defeault ubuntu repositories).

**Comment by evoskuil** [comment]
Hi @streamofstars, thanks for reporting. Keep in mind that this is a FOSS project. Issues and suggestions are always welcome but pull requests get more love than a list of demands.

**Comment by evoskuil** [comment]
Reduced libzmq dependency and build to 4.2.0, added --help to install.sh.
