### ISSUE TITLE
Really slow initial block sincyng

### ISSUE THREAD

**Issue by Bedotech** [libbitcoin/libbitcoin-server#441]
Hi all,

First of all thanks for the great product!
I already have read the wiki about performance hardware and initial config, my machine have the following specs:
* Intel i7-8700x (12 core)
* 32GB Ram
* Electronics NVMe SSD Controller SM961/PM961 as disk.

So i think my machine is in the middle of big and small server, the disk is really fast, i monitor my machine with netdata and when libbitcoin-server is launched i have this scenario:
![image](https://user-images.githubusercontent.com/627329/37019670-78a1ce3e-2119-11e8-8bd0-cc4811d5eeb4.png)
(only libbitcoin is running)

As you can see the purple is iowait, this graph is the same for all 12 cores.

I only want ask if this behavior is in the normal range because it takes really a lot of time (over 1 week) for the initial syncing with a 30mb/s bandwith.

**Comment by evoskuil** [comment]
Hi @Bedotech. If you are validating (vs. checkpoints) then full CPU utilization is desirable and expected. The initial block download aspect of the v3 node is very simple and slow, [see FAQ](https://github.com/libbitcoin/libbitcoin-server/wiki/Frequently-Asked-Questions#q-how-efficient-is-initial-block-download). However a week seems high, I would expect about 24 hours on your machine, though the bandwidth is quite a bit lower than I'm used to working with.

Initial block download has been a major area of work in v4. I'm presently able to fully sync mainnet in 2 hours and 15 minutes on my box, and I expect that time to come down more. This was deferred in v3 so this area is really not up to the level of performance level of the reset of the stack.

**Comment by Bedotech** [comment]
Thanks @evoskuil i do my home work and try to find more info on why my hardware is so slow.

Only one question, i notice from the log (after i take more detailed data on this) that block download is esponential.

After the last checkpoint the block validation and download seems increas at each block, is normal? 

This week i repeat the test with the upcoming release and post here the difference! thanks!

**Comment by evoskuil** [comment]
> After the last checkpoint the block validation and download seems increas at each block, is normal?

Yes, validation is very costly.

> After the last checkpoint the block validation and download seems increas at each block, is normal?

Blocks go from ~1KB to ~1MB on average, which is 3 orders of magnitude more computation per block.

**Comment by streamofstars** [comment]
I will piggyback on this thread, I might have a similar issue. Actually it is hard to say, unless I am missing something... Does bs report somehow that it finished the initial blockchain syncing or should I figure that out myself by checking in third party sources how big the blockchain is currently and comparing that the downloaded data stats?

**Comment by thecodefactory** [comment]
@streamofstars How do you mean report?  It shows via output and logging which block it has processed as it goes.  If it's current (i.e. in consensus with the network at the time), it's caught up -- until another block is discovered, in which case it keeps processing.

**Comment by streamofstars** [comment]
@thecodefactory of course in the terminal, it shows the block height but without any reference to the actual number of blocks available in the network. When you run the server for the first time and do not check in external sources (e.g. blockchain.info) how many blocks are there, you have no idea at which point of syncing you are.

**Comment by evoskuil** [comment]
There is no better external source of truth than the node itself. It gets its information from the p2p network, just like blockchain.info. It is often ahead of their website, which tends to be slow to process and report blocks.

**Comment by evoskuil** [comment]
It is possible to see via the debug log when the node believes it is caught up with each peer. However there is no way to know that peers have the most recent and most difficult blocks. Often they do not, but consistency is reached very quickly unless you have been partitioned off of the network.

**Comment by thecodefactory** [comment]
Closing (first response answers the question).  Can re-open if still needed for v4.
