### ISSUE TITLE
Server isn't listening on endpoints

### ISSUE THREAD

**Issue by periodic1236** [libbitcoin/libbitcoin-server#45]
My local server on Ubuntu 14.04.1 managed to finish syncing today, but I noticed it won't actually respond to requests from BX. I have all the default port settings and set my BX config to use `url = tcp://localhost:9091`. However, output of `netstat` doesn't show any of the relevant ports.

I looked through the worker.cpp code and didn't find anything obvious. Is this supposed to be working right now? I realize it's still very much in development, but the server doesn't seem very useful without its service endpoint.

I can provide logs and other information about my setup if needed.

**Comment by periodic1236** [comment]
As a sidenote, I tried turning on the publisher, but that results in an immediate error when launching the server.
```
~ $ bitcoin_server
Publisher failed to start: Invalid argument
terminate called without an active exception
[1]   <pid> abort      bitcoin_server
```

**Comment by evoskuil** [comment]
The server is broken (see https://github.com/libbitcoin/libbitcoin-server/issues/42), however it you get it synced it may respond.

**Comment by evoskuil** [comment]
The publisher issue could be unrelated. I haven't been able to get synced to test out the later config changes.

**Comment by evoskuil** [comment]
I repro'd the publisher issue, so I can track that down independently. Could you move that to a distinct issue?

**Comment by periodic1236** [comment]
I ran into something similar to #42 on my first try a few days ago, but now I'm fully synced. I have 32GB of RAM so the memory issue is not as bad.

I see you're still fleshing out the config framework - is it still likely that some of your recent changes may have broken the worker? I would expect it to work since I'm synced, but again `netstat` suggests the server isn't even listening on any port besides 8333.

> I repro'd the publisher issue, so I can track that down independently. Could you move that to a distinct issue?

Sure.

**Comment by evoskuil** [comment]
Yes, the config changes to publisher weren't verified, probably just because it's off by default and the larger blockchain issue is outstanding.

**Comment by evoskuil** [comment]
The fact that you got sync'd is pure luck. The indexer is hosed up, and runs around in allocated memory until it causes a wreck (or not). The history index is therefore AFU even if you are synced.

**Comment by periodic1236** [comment]
I see. I can wait for you to work on the blockchain issues then. Thanks for the prompt response!

**Comment by veox** [comment]
This is a regression from commit 8c881cf3, which introduced `endpoint_type`. The endpoint string is not being read correctly: specifying `tcp://*:9091` results in endpoints of form `tcp:\*:9091`.

This is valid for both this issue and #46.

In the case of service ports, checks for ZMQ binding success seem to be different from those of publisher ports.

I've figured out a partial workaround, but will try to rework to fit both cases.

**Comment by evoskuil** [comment]
Hi @periodic1236, Just out of curiosity, how large is your blockchain database (excluding logs) and how much RAM is consumed by the process now that it's sync'd?

**Comment by periodic1236** [comment]
@evoskuil My blockchain database is at 98.6GiB and the process consumes about 60M of physical memory (99.4G virtual).

**Comment by periodic1236** [comment]
My obelisk DB synced up to within the last week was about 70GiB though.

**Comment by periodic1236** [comment]
I take back the RAM consumption figure - it varies of course. I tried querying for the balance of a high-volume address, 1VayNert3x1KzbpzMGt2qdqrAThiRovi8, and it invariably times out while causing RAM usage to spike to 700M+. The server then fails to respond to other balance commands (I don't know if it's still computing a response). This is probably #42 then.

SX used to succeed on this address, albeit returning an impossible answer: https://github.com/spesmilo/sx/issues/87

**Comment by evoskuil** [comment]
This is a good confirmation of what I would expect. Given that the history index is bad, history and balance queries (at least) should fail. How they fail is up to fate. I hadn't been able to repro this however, since the same issue generally results in a failure before completion of initial sync.
