### ISSUE TITLE
Tiniest update on the Query Service wiki

### ISSUE THREAD

**Issue by haarts** [libbitcoin/libbitcoin-server#453]
On the [Query Service](https://github.com/libbitcoin/libbitcoin-server/wiki/Query-Service#subscribeaddress) page the `subscribe.address` returns a notification. That notification has 4 fields of which the last is said to be a `block hash`. It is not, it is actually a `transaction hash`. 
I can't seem to edit the wiki therefor this issue.

**Comment by evoskuil** [comment]
Scroll to the right of the block hash in the message description.

**Comment by haarts** [comment]
:man_facepalming: 
I just got twins, can I use that as a piss poor excuse?

**Comment by evoskuil** [comment]
Yes
