### ISSUE TITLE
Cannot get last height through python

### ISSUE THREAD

**Issue by mayaomichael** [libbitcoin/libbitcoin-server#458]
Per below I cannot get last height with python 3.

```py
#!python3
import zmq
import struct
from binascii import hexlify

# The default unsecured mainnet community server address.
server_url = "tcp://mainnet.libbitcoin.net:9091"

request_command = b'blockchain.fetch_last_height'

# The arbitrary message id is for client response correlation.
request_id = struct.pack('I', 42)

# Connect to the server with 5 second timeouts.
context = zmq.Context()
socket = context.socket(zmq.REQ)
socket.setsockopt(zmq.RCVTIMEO, 5000)
socket.setsockopt(zmq.SNDTIMEO, 5000)
socket.connect(server_url)
    
# Make the request in parts.
socket.send(request_command, zmq.SNDMORE)
socket.send(request_id, zmq.SNDMORE)
# socket.send(blockHeight)

# Collect the response in parts.
response_command = socket.recv()
response_id = socket.recv()
response_body = socket.recv()
```

**Comment by thecodefactory** [comment]
@mayaomichael  What is the error that you're seeing?

**Comment by mayaomichael** [comment]
Plz see below thanks!

    response_command = socket.recv()
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq\backend\cython\socket.c:7683)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq\backend\cython\socket.c:7460)
  File "zmq/backend/cython/socket.pyx", line 150, in zmq.backend.cython.socket._recv_copy (zmq\backend\cython\socket.c:2437)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq\backend\cython\socket.c:2344)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:10014)
    raise ZMQError(errno)
zmq.error.ZMQError: Operation cannot be accomplished in current state

**Comment by thecodefactory** [comment]
@mayaomichael I don't think this has anything to do with python3 vs python2.  See if this sample program helps.  I've tried to comment it to better describe what is being sent/received.

```
#!python3                                                                                                                                   
import zmq
import struct

context = zmq.Context()
socket = context.socket(zmq.REQ)
socket.connect('tcp://mainnet.libbitcoin.net:9091')

# Request format is: command, id, payload
request_command = b'blockchain.fetch_last_height'
request_id = struct.pack('<I', 1)
request_payload = b''

socket.send(request_command, zmq.SNDMORE)
socket.send(request_id, zmq.SNDMORE)
socket.send(request_payload);

# Response format is: command, id, payload
response_command = socket.recv()
response_id = socket.recv()
response_body = socket.recv()

# "response_body" format is: error_code, block_height
error_code = int.from_bytes(response_body[0:4], byteorder='little', signed=False)
height = int.from_bytes(response_body[4:], byteorder='little', signed=False)

print('Error code {}'.format(error_code))
print('Block height {}'.format(height))
```

**Comment by mayaomichael** [comment]
Thanks it's working now. I forgot to send the empty payload below:

socket.send(request_payload);
