### ISSUE TITLE
Fetch Block Height Wiki not Update to Date?

### ISSUE THREAD

**Issue by mayaomichael** [libbitcoin/libbitcoin-server#459]
On the [Query Service](https://github.com/libbitcoin/libbitcoin-server/wiki/Query-Service#blockchainfetch_block_height) page, fetch_block_height doesn't seem to be working. Should be fetch_last_height.

**Comment by evoskuil** [comment]
They are different queries with different request parameterizations.

**Comment by mayaomichael** [comment]
My bad misunderstood.
