### ISSUE TITLE
Publisher fails to start with invalid argument exception

### ISSUE THREAD

**Issue by periodic1236** [libbitcoin/libbitcoin-server#46]
I tried turning on the publisher, but there's an immediate error during launch.
```
~ $ bitcoin_server
Publisher failed to start: Invalid argument
terminate called without an active exception
[1]   <pid> abort      bitcoin_server
```

**Comment by evoskuil** [comment]
Reproduced on Linux and Windows. Thanks for filing!

**Comment by evoskuil** [comment]
The failure percolates up from the following call in zmq.cpp:
```c
int zmq_bind (void *s_, const char *addr_)
{
    if (!s_ || !((zmq::socket_base_t*) s_)->check_tag ()) {
        errno = ENOTSOCK;
        return -1;
    }
    zmq::socket_base_t *s = (zmq::socket_base_t *) s_;
    int result = s->bind (addr_);
    return result;
}
```

The `s->bind(addr_)` call is parameterized with `tcp:\\*:9093` (from default config) and returns `-1' (failure).

**Comment by evoskuil** [comment]
This may result from a mis-configuration of the socket during recent config-related work. If so it may explain https://github.com/libbitcoin/libbitcoin-server/issues/45 as well.
