### ISSUE TITLE
Add 'version' command to the Query Service

### ISSUE THREAD

**Issue by haarts** [libbitcoin/libbitcoin-server#468]
This is a feature request.

The command would return the version of the responding libbitcoin-server. 
Adding this command would be useful for clients wanting to tell their users to what backends they are talking to. 
This request is immediately inspired by the [similar call](https://electrumx.readthedocs.io/en/latest/protocol-methods.html#server-version) supported by ElectrumX.

**Comment by thecodefactory** [comment]
> This request is immediately inspired by the similar call supported by ElectrumX.

:+1: But just to be clear, are we looking at a standalone version command that is queried, or a protocol change that requires version exchange on all commands and terminates the connection if incompatible?  Both are useful (the first allows the client to query around to find a suitable node or satisfy a curiosity, but the second attempts to enforce protocol compatibility).

**Comment by evoskuil** [comment]
Good question, the former.

**Comment by thecodefactory** [comment]
> Good question, the former.

Ok, I think that's most straight-forward.  The client can then either just report the server version, or match what's returned with its own version and report on differences if found.  Perhaps by default the latter and with an option the former?
