### ISSUE TITLE
Cannot connect to bitcoin-core peers

### ISSUE THREAD

**Issue by swansontec** [libbitcoin/libbitcoin-server#50]
I am telling the server to connect to a specific peer via a command in the config file:

    peer = obelisk-sol2.airbitz.co:8334

Sadly, this doesn't work. The libbitcoin-server program spews a bunch of lines like these:
```
22:39:42.759410 INFO [protocol]: Manual connection established: obelisk-sol2.airbitz.co:8334
22:39:42.760244 ERROR [protocol]: Channel stopped (manual): Service stopped
22:39:42.760368 ERROR [poller]: Send problem: Service stopped
```
The Satoshi peer (`Bitcoin Core Daemon version v0.10.0.0-g047a898`) spews lines like these to its `~/.bitcoin/debug.log`:

    2015-02-27 22:44:01 receive version message: /libbitcoin:2.8.0/: version 60000, blocks=17457, us=10.0.0.1:8333, peer=67546

This isn't a connectivity problem, since the two servers obviously see each other. They just aren't able to negotiate a handshake. I can't get any success the other way around either (adding the libbitcoin peer to the Satoshi `~/.bitcoin/bitcoin.conf`).

**Comment by swansontec** [comment]
The bug affects every version of libbitcoin-server/obelisk that I tested, from version1 to the absolute latest version from yesterday.

**Comment by evoskuil** [comment]
Good to know.  I do see these errors when syncing, sometimes heavily, sometimes not so much, even without explicitly specifying any peers. The peer configuration is documented as augmenting peers discovered from the seed list. So one possible interpretation is that the error is more general than peer configuration but may not happen with all connections. If so it might be worth identifying a connection that is not working and one that is working, for the sake of comparison. If there is 100% success on one and 100% failure on the other, it may help identify the issue.

**Comment by swansontec** [comment]
libbitcoin/libbitcoin@bb430e2f seems to fix this, so I'll go ahead and close this.
