### ISSUE TITLE
Seed servers down?

### ISSUE THREAD

**Issue by bitcoinextw** [libbitcoin/libbitcoin-server#500]
have been trying to run bs since yesterday. seed server mainnet2 and 4 is down. there is only one ip address in the host.cache downloaded.

anyone gets this issue too?

**Comment by thecodefactory** [comment]
Strange, mainnet2 should not be down.  mainnet4/testnet4 have been down for some time.  So in the meantime, try mainnet1/mainnet2/mainnet3.  What version are you running?

**Comment by bitcoinextw** [comment]
yes, it works now. thank you very much.
