### ISSUE TITLE
Testnet3 chain stops syncing at block 4032

### ISSUE THREAD

**Issue by swansontec** [libbitcoin/libbitcoin-server#51]
It appears that block 4033 contains something libbitcoin disagrees with, so the sync simply stops:

    Storing block 00000000db623a1752143f2f805c4527573570d9b4ca0a3cfe371e703ac429aa: Proof of work does not match bits field

**Comment by evoskuil** [comment]
The issue most likely arises from `uint32_t validate_block::work_required()` in `libbitcoin-blockchain`.

**Comment by veox** [comment]
I have built an hour ago (Ubuntu 14.04.2, commit f2bf117f), and do not experience this.

**Comment by veox** [comment]
So, is this reproducible?..

**Comment by evoskuil** [comment]
I haven't tried it yet.

**Comment by evoskuil** [comment]
I can't repro using the `--without-consensus` blockchain option (which would now be required to repro the same scenario). Ubuntu `install.sh` with `--enable-testnet` `--enable-ndebug` `--with-consensus`.

**Comment by evoskuil** [comment]
Is this issue resolved? I was never able to reproduce it.

**Comment by veox** [comment]
IMO OK to close. Couldn't reproduce either. Have re-synced ~4 times since then (most recent ~week ago).

**Comment by evoskuil** [comment]
Great, thanks! With or without libbitcoin-consensus?

**Comment by veox** [comment]
With libbitcoin-consensus (using defaults, satoshi's consensus).

**Comment by swansontec** [comment]
I built a new tesnet server from scratch using the latest release and `--disable-consensus --enable-testnet`. It was able to sync the entire chain without trouble. I don't know what went wrong with that first one, but it's fixed now.

**Comment by evoskuil** [comment]
For the sake of clarity, the switch to not use libbitcoin-consensus is `--without-consensus`, so that would have been a test using the consensus lib.

**Comment by thecodefactory** [comment]
I'd like to test this in both configurations (with and without consensus), and I'll report back with the results. I know it's already closed ... and I hope it stays that way.

**Comment by swansontec** [comment]
Oh, sorry. It was `--without-consensus`. I typed the bug report from memory, but the config script shows that I used the right one.

**Comment by thecodefactory** [comment]
I can also confirm testnet syncs to current with a fresh build of testnet with consensus.

**Comment by evoskuil** [comment]
Well it looks like we don't have the Core Testnet bug :).

**Comment by thecodefactory** [comment]
Yes, it's good news!  I have a sync going now on a separate build w/o consensus also.  Will report back when it completes (perhaps tomorrow).

**Comment by thecodefactory** [comment]
And for completeness, a fresh testnet build without consensus also syncs entirely.

**Comment by veox** [comment]
I've gotten this again. Restarting the server fails on the same block. Rebuilding (`install.sh --enable-testnet --prefix=...`, default consensus, system's boost) results in failure on a different block, but always early in the sync process (around block 4000 or so).

Possibly related to https://github.com/libbitcoin/libbitcoin-blockchain/pull/85
