### ISSUE TITLE
Generating blocks in regtest chain config

### ISSUE THREAD

**Issue by h4v0kr** [libbitcoin/libbitcoin-server#515]
Hi @evoskuil and team!

I'm in the process of writing a tutorial for using the libbitcoin stack, and have successfully configured a community node in regtest mode as suggested here:

https://github.com/libbitcoin/libbitcoin-server/wiki/Regtest-Configuration

I'm familiar with bitcoin core and bcoin regtest and simnet configuration, and how to generate blocks using the cli e.g. bitcoin-cli generate nBlocks etc.

How do I go about doing this with the regtest config for the libbitcoin server?

Really appreciate any feedback and time for responding :D 

Bitcoin Developer Network
https://bitcoindev.network

**Comment by thecodefactory** [comment]
@h4v0kr Glad to hear!  For now, the most straight-forward way is to connect your regtest node to a bitcoind node (also running in regtest mode) and then mine using that external node (using generate as you mentioned).  There is no direct mining path available on the libbitcoin node at the moment, but it's on the roadmap.

**Comment by h4v0kr** [comment]
Thanks, @thecodefactory, will revert back once I've got it working :D much appreciated!

**Comment by evoskuil** [comment]
What is the open issue?

**Comment by h4v0kr** [comment]
Alrighty, so, I've finally got this working, however... few comments

the documentation on the wiki needs a change

https://github.com/libbitcoin/libbitcoin-server/wiki/Regtest-Configuration

Here we have a [flags] section which needs to be changes to [fork] :D

Secondly, this does not work with bitcoin core < 16. I've tested this successfully with version bitcoin-0.15.2

```
gr0kchain@bitcoindev $ bs --version

Version Information:

libbitcoin-server:     3.4.0
libbitcoin-protocol:   3.4.0
libbitcoin-node:       3.4.0
libbitcoin-blockchain: 3.4.0
libbitcoin:            3.4.0
gr0kchain@bitcoindev $ ./bitcoin-0.15.2/bin/bitcoin-cli --version
Bitcoin Core RPC client version v0.15.2
gr0kchain@bitcoindev $ bitcoin-cli generate 101
gr0kchain@bitcoindev $ bx fetch-height tcp://localhost:9091
101
```

This, however, DOES NOT work with a version including 0.16 and 0.17.

```
gr0kchain@bitcoindev $ bs -c ~/.config/bs/regtest.conf
21:42:42.494281 INFO [server] ================= startup  ==================
21:42:42.494320 WARNING [server] ================= startup  ==================
21:42:42.494439 ERROR [server] ================= startup  ==================
21:42:42.494477 FATAL [server] ================= startup  ==================
21:42:42.494519 INFO [server] Using config file: "/Users/h4v0k/.config/bs/regtest.conf"
21:42:42.494552 INFO [server] Please wait while the server is starting...
21:42:42.496005 INFO [network] Starting manual session.
21:42:42.496105 INFO [network] Not configured to populate an address pool.
21:42:42.496148 INFO [server] Seeding is complete.
21:42:42.496225 INFO [node] Node start height is (0).
21:42:42.496334 INFO [network] Not configured for accepting incoming connections.
21:42:42.496363 INFO [network] Starting outbound session.
21:42:42.497167 WARNING [network] Failure fetching new address: object does not exist
21:42:42.497990 INFO [server] Bound public query service to tcp://*:9091
21:42:42.498602 INFO [server] Bound public heartbeat service to tcp://*:9092
21:42:42.498879 INFO [server] Bound public block service to tcp://*:9093
21:42:42.499139 INFO [server] Bound public transaction service to tcp://*:9094
21:42:42.499195 INFO [server] Server is started.
21:42:42.504696 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
```

This sits here until you generate a block, and floods the terminal wil 

```
21:43:25.999302 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
21:43:26.017903 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
21:43:26.036815 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
21:43:26.053534 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
21:43:26.071378 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
21:43:26.091038 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
21:43:26.109701 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
21:43:26.127973 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
21:43:26.147907 INFO [network] Connected manual channel [localhost:18444] as [127.0.0.1:18444] (1)
```
and the bitcoind debug.log with

```
2019-02-22 21:43:26 Cleared nodestate for peer=87
2019-02-22 21:43:26 Added connection to 127.0.0.1:57865 peer=88
2019-02-22 21:43:26 connection from 127.0.0.1:57865 accepted
2019-02-22 21:43:26 received: version (104 bytes) peer=88
2019-02-22 21:43:26 sending version (102 bytes) peer=88
2019-02-22 21:43:26 send version message: version 70015, blocks=1, us=[::]:0, them=[::]:0, peer=88
2019-02-22 21:43:26 sending verack (0 bytes) peer=88
2019-02-22 21:43:26 receive version message: /libbitcoin:3.4.0/: version 70013, blocks=0, us=127.0.0.1:18444, peer=88, peeraddr=127.0.0.1:57865
2019-02-22 21:43:26 received: verack (0 bytes) peer=88
2019-02-22 21:43:26 sending sendheaders (0 bytes) peer=88
2019-02-22 21:43:26 sending ping (8 bytes) peer=88
2019-02-22 21:43:26 initial getheaders (0) to peer=88 (startheight:0)
2019-02-22 21:43:26 sending getheaders (69 bytes) peer=88
2019-02-22 21:43:26 received: ping (8 bytes) peer=88
2019-02-22 21:43:26 sending pong (8 bytes) peer=88
2019-02-22 21:43:26 received: sendheaders (0 bytes) peer=88
2019-02-22 21:43:26 received: getheaders (69 bytes) peer=88
2019-02-22 21:43:26 getheaders 1 to end from peer=88
2019-02-22 21:43:26 sending headers (82 bytes) peer=88
2019-02-22 21:43:26 received: feefilter (8 bytes) peer=88
2019-02-22 21:43:26 received: feefilter of 0.00000189 BTC/kB from peer=88
2019-02-22 21:43:26 received: pong (8 bytes) peer=88
2019-02-22 21:43:26 received: getdata (37 bytes) peer=88
2019-02-22 21:43:26 received getdata (1 invsz) peer=88
2019-02-22 21:43:26 received getdata for: witness-block 534be010af1b8cd9d36411652f124aac1edf842ba33bd96a3dcd570867d92ffc peer=88
2019-02-22 21:43:26 sending block (262 bytes) peer=88
2019-02-22 21:43:26 socket closed
2019-02-22 21:43:26 disconnecting peer=88
```

Thought I'd bring this to your attention, took me a while to figure out, but thanks to @evoskuil's comments here, I did a sanity check based on the last working version tested with https://github.com/libbitcoin/libbitcoin-server/issues/404

**Comment by h4v0kr** [comment]
Feel this is more informative than just saying that the following always returns 0 unless you use one of the working bitcoind versions

```
gr0kchain@bitcoindev $ bx fetch-height tcp://localhost:9091
0
```

**Comment by h4v0kr** [comment]
Here is my config as a sanity check 

```
gr0kchain@bitcoindev $ cat ~/.config/bs/regtest.conf
[network]
# The magic number for message headers.
identifier = 3669344250

# The port for incoming connections.
inbound_port = 18445

# Disable seeding, otherwise manually populate hosts.cache file.
host_pool_capacity = 0

# Optionally connect to one or more peers on a private regtest network.
peer = localhost:18444

[blockchain]
# Disable default (mainnet) checkpoints.
checkpoint = 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206:0

[fork]
# Retarget difficulty, defaults to true (use false for regtest).
retarget = false

# Require coinbase input includes block height (disabled on satoshi client).
bip34 = false```

**Comment by evoskuil** [comment]
The documentation is for version3 (production code).

**Comment by h4v0kr** [comment]
I see, still need to understand the difference here, was under the impression the tags where considered production https://github.com/libbitcoin/libbitcoin-server/tree/v3.4.0

I am currently running a version I'd installed using brew on mac os x. Tried compiling a version of master on both linux and os x, but running into other issues which I'll keep looking into on my own time. 

Do we know if the current version3 production code works with core 0.17.1?

**Comment by evoskuil** [comment]
Only versioned branches include tagged commits.

**Comment by h4v0kr** [comment]
Excuse my ignorance, but could you define what you mean by version3 (production code)? 

Not finding any definition of this on the FAQ or README for the project. Any references you could point me to would be appreciated

**Comment by h4v0kr** [comment]
Unless you're referring to the major version 3.0 being your production code, and minor increments being development? e.g. 3.1?

**Comment by evoskuil** [comment]
Each major version is represented by a branch. Master is staging for future major versions.

**Comment by h4v0kr** [comment]
Ah! There I see it now :D Thanks @evoskuil. After downloading this version the binary from https://github.com/libbitcoin/libbitcoin-explorer/releases/tag/v3.0.0 however, it complains when using either flags or fork

```
gr0kchain@bitcoindev $ ~/Downloads/bs-osx-x64 --version

Version Information:

libbitcoin-server:     3.0.0
libbitcoin-protocol:   3.0.0
libbitcoin-node:       3.0.0
libbitcoin-blockchain: 3.0.0
libbitcoin:            3.0.0
gr0kchain@bitcoindev $ ~/Downloads/bs-osx-x64 -c ~/.config/bs/regtest.conf
Error: unrecognised option 'flags.retarget'
gr0kchain@bitcoindev $ ~/Downloads/bs-osx-x64 -c ~/.config/bs/regtest2.conf
Error: unrecognised option 'fork.retarget'
```

**Comment by evoskuil** [comment]
See forks documentation. You are .4 versions too old for .retarget. I strongly recommend building from the head of version3 or at least the most recent tags (not the first v3 release).

**Comment by h4v0kr** [comment]
Thanks @evoskuil, linking this at the bottom. As suggested here, my original 3.4 version of BS installed via brew on mac os x does work when using [fork] instead of [flags], and only with versions of bitcoin core <= 0.15. I'll close this for now 

https://github.com/libbitcoin/libbitcoin-server/wiki/Fork-Settings

**Comment by Bitmonkeyp** [comment]
... there is always possibility to mine off line ... ./bitcoind -server -listen -port=17599 -rpcuser=home -rpcpassword=faraway -rpcport=6991 \
-datadir="$HOME/.bitcoin0" -connect=localhost:8333 \
-pid="/$HOME/.bitcoin0/.pid" -printtoconsole -daemon -debug -txindex -gen
