### ISSUE TITLE
abnormal stop. error: what():  cancel: Bad file descriptor

### ISSUE THREAD

**Issue by john-shine** [libbitcoin/libbitcoin-server#533]
When I try to stop server with sign ctrl-c, server stop abnormal, database lock file still exist after exit. Here is logs:

Nov 19 23:20:35 blockchain-server-2 systemd[1]: Stopping Libbitcoin-server daemon service...
Nov 19 23:20:35 blockchain-server-2 bs[15932]: 15:20:35.147944 INFO [server] Stop signal detected (code: 15).
Nov 19 23:20:35 blockchain-server-2 bs[15932]: 15:20:35.988522 INFO [server] Please wait while the server is sto
Nov 19 23:20:36 blockchain-server-2 bs[15932]: terminate called after throwing an instance of 'boost::wrapexcept
Nov 19 23:20:36 blockchain-server-2 bs[15932]:   what():  cancel: Bad file descriptor

software Version Information:

libbitcoin-server:     4.0.0
libbitcoin-protocol:   4.0.0
libbitcoin-node:       4.0.0
libbitcoin-blockchain: 4.0.0
libbitcoin:            4.0.0

**Comment by evoskuil** [comment]
Possibly: https://github.com/libbitcoin/libbitcoin-system/issues/766

**Comment by john-shine** [comment]
I disable log logrotate with rotation_size = 0, error still exists. I thinks it's not the same issue as 776.

**Comment by evoskuil** [comment]
What do you mean by “still exists”?

**Comment by john-shine** [comment]
I means disable logrotate and reproduce the situation that stop server with sign ctrl-c, there still remain same error. So, things not contact with logrotate.

**Comment by john-shine** [comment]
I build libbitcoin-server with last version boost from official boost.org. After read some codes, I thinks it's not compatible with libbitcoin-server v4.0.0

**Comment by evoskuil** [comment]
Turning off log rotation does not turn off logging. Keep in mind that people run v4 without experiencing this problem. And it’s never been consistently of frequently reproducible.

**Comment by evoskuil** [comment]
Reason for closing?
