### ISSUE TITLE
Properly freeing up old libbitcoin-server/etc/libbitcoin/blockchain disk space?

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-server#58]
I tried to reuse a libbitcoin-server files from a build created about 60 days ago with a new build from code freshly downloaded all at once last night. I got a segmentation fault after OSX requested that I authorize the servers ports. So then I decided to delete the old blockchain with a "rm -fr blockchain", and start fresh only to find out a "df" indicated my MacBookPro did not have any filesystem disk space freed up.  Somewhere around 80GB from a 256GB solid state disk drive is now in limbo.  Any suggestions for regaining the disk space? (A disk drive lobotomy really kills the mood to experiment and learn...)

FYSA - I created the blockchain directory in my libbitcoin-server/etc/libbitcoin/ directory with "mkdir blockchain" then I executed the libbitcoin-blockchain/bin/initchain in the same directory as the mkdir. This allowed me to execute "../../bin/bitcoin-server" to have the blockchain built. Was within 20K blocks of having a full obelisk node built, but started to realize the MacBookPro was tending to run hot and slowed way... down. This was the motivation to make a brand new build with the latest code base using my own build scripts after figuring out what https://github.com/libbitcoin/libbitcoin-server/blob/master/install.sh was really accomplishing. I noticed that the latest code has openssl package dependencies (specifically crypto_CFLAGS and crypto_LIBS).  Everything in the new build used the version2 branch except that for the new libbitcoin-consensus package that was based upon its version1 branch.

**Comment by evoskuil** [comment]
Hi @skaht,

It's not surprising that a new build segfaulted against a blockchain database from a previous build. The effective structure of the database was changing.

As for why OSX failed to free the space after deleting the files, no idea but I have to assume it's an OS failure. There's nothing special about the storage, just files in a directory.

As for recovering that space, presumably there are OSX disk repair utilities that can rebuild the directory without having to reformat the drive.

The server doesn't throttle its thread priority, so it tends to consume most of the resources on a machine. But previous builds had problems that caused a great deal of churn and/or failures that could exacerbate that situation. The current pending release is much more reasonable.

Yes, the latest build optionally requires openssl as a requirement of incorporating the consensus library. You can remove that dependency using `--without-consensus` on the `libbitcoin-blockchain` build (or from the install.sh).

**Comment by veox** [comment]
As to `libbitcoin-consensus` (which you might avoid as described above) being `version1`,  that's because this is the first release of this library. It might be a bit confusing, but version branches are for keeping track of (in)compatibility within a sub-project, not throughout the toolchain. A versioning document is available at [libbitcoin-build/documentation](https://github.com/libbitcoin/libbitcoin-build/blob/master/documentation/versioning.pdf).

Also, `initchain` is now `libbitcoin-server --initchain`.

**Comment by skaht** [comment]
Evoskuil and Veox,

Thanks for the assistance:-) 

Unfortunately, Apple's /Applications/Utilities/Disk\ Utility did not fix the issue:-( Will try the Apple help desk to find out if their default case insensitive journaling FS with encryption on flash has a bug with large files being removed as a regular user.

Been out of the UNIX S/W development groove since 1998. Nothing like trial by fire for relearning old UNIX skills in a Mac environment... Will have to brush up on my C++ skills.

**Comment by skaht** [comment]
It turns out that running http://www.derlien.com/downloads/ "Disk Inventory X" indicates the disk is freed up while "df -k" or an (About This Mac)->(Storage tab) indicates otherwise. Time machine never tried to backup the blockchain when after it was removed. This is starting to look like an OSX feature/bug. Still have another 10 months on the warranty. Will push the disk space limit to see if it is really a "df" OSX implementation bug.
