### ISSUE TITLE
Blockchain forking with libbitcoin-consenus

### ISSUE THREAD

**Issue by swansontec** [libbitcoin/libbitcoin-server#61]
At random points during normal operation, the blockchain will stop syncing. During one particular instance, error.log showed:

```
15:09:10.960411 WARNING [validate]: Input script consensus validation failed
15:09:10.960601 WARNING [validate]: Validate input 46581355dad0b59ac492d9df490292d5311776aac0c5164c8e14fe32012ce43a:1 failed
15:09:10.960745 WARNING [poller]: Storing block 000000000000000009e531e76f8a1c35829b663eef46158ed3505c134a5d6319: Validation of inputs failed
```

Rebuilding the libbitcoin-blockchain part `--without-consensus` seemed to clear this up, and the chain started syncing again:

    16:59:52.077616 INFO [poller]: Block #351252 000000000000000009e531e76f8a1c35829b663eef46158ed3505c134a5d6319

I've had this happen twice now, both at different points in the blockchain.

**Comment by evoskuil** [comment]
I haven't verified that the consensus lib works with testnet, prob not.

**Comment by swansontec** [comment]
This is mainnet.

**Comment by evoskuil** [comment]
With OpenSSL? If so which version?

**Comment by swansontec** [comment]
1.0.1f-1ubuntu2.11

The consensus for supposedly happened in 1.0.1k, IIRC. Maybe Ubuntu backported the breakage or something.

**Comment by evoskuil** [comment]
We should require the correct min version, but I don't know if their lettering scheme for minor versions works with pkg-config versioning.

e

**Comment by arnuschky** [comment]
In short: yes, they do backport and you have it. Revert back to 1.0.1f-1ubuntu2.7.

See https://bitcointalk.org/index.php?topic=919373.msg10282205#msg10282205

**Comment by arnuschky** [comment]
(how is described further down in that thread)

**Comment by evoskuil** [comment]
Was this resolved by using `OpenSSL 1.0.1f-1ubuntu2.7`?

**Comment by evoskuil** [comment]
This was still an issue, should be resolved by:

https://github.com/libbitcoin/libbitcoin-blockchain/commit/4e41ba7a5c884c0e3268d90ea4f2a838e7fe7cb4#diff-163d5cf7d56a2dee6a59490f0e0da0a2L60

Which eliminates the incorrect requirement of validation against "standard" flags when using `libbitcoin-consensus`.

**Comment by evoskuil** [comment]
I just passed the block mentioned at the opening above and had no problems.
