### ISSUE TITLE
Failed to store transaction in mempool: Spent input not found

### ISSUE THREAD

**Issue by atweiden** [libbitcoin/libbitcoin-server#77]
The recent changes make a world of difference. I was syncing past block 330,000 with no problem, albeit slowly (2-3 blocks per min) and so today I started over from block zero for testing. All ran smoothly until block 92603, where I began seeing this warning:

```
16:58:34.615363 WARNING [node]: Failed to store transaction in mempool 6337eafeafedf2df5599431b4b4b7946a7baa2e12e52f7cb2b99dbf4cedd1ee9: Spent input not found
16:58:34.681852 WARNING [node]: Failed to store transaction in mempool 543db7c66df7074736309dcff65aea21a4751013736a7d45993350b40b602b4e: Spent input not found
16:58:36.713706 WARNING [node]: Failed to store transaction in mempool fff32b926f2869fccb67633b860a5177c22aac7ed57f88272cd9f7363991b852: Spent input not found
16:58:36.905803 WARNING [node]: Failed to store transaction in mempool 3160cd35e198c5bc3ff8d6d964e93dec908e8db2b3b9dfa443830bbbc3ff4144: Spent input not found
16:58:37.283318 WARNING [node]: Failed to store transaction in mempool aa3ac61bde0ff5b2f7630624be316c1a7fa4ff83e39ff284500a89ec94ffdd03: Spent input not found
16:58:38.207241 WARNING [node]: Failed to store transaction in mempool a4abb98660068f65260568755d2540f7a817d0046bf49febe56680a2e749b983: Spent input not found
```

(i am running entire libbitcoin suite built from latest git master)

**Comment by atweiden** [comment]
Update: this seemed to halt syncing progress for several minutes, which is when I opened this issue. `bs` has since made it past block 92603, so this is probably not of much concern.

**Comment by evoskuil** [comment]
This is to be expected, although it is always possible it's happening when it shouldn't.

**Comment by evoskuil** [comment]
Thanks for testing and for the feedback.

It is also expected that it may coincide with delays and increased memory consumption (up to a point), since the txs are being held up in memory.

**Comment by evoskuil** [comment]
This is a normal indication of a transaction receipt from the network when the blocks that its inputs refer to have not yet been synced. SeeL https://github.com/libbitcoin/libbitcoin-node/pull/41
