### ISSUE TITLE
Torify obelisk protocol connections.

### ISSUE THREAD

**Issue by venzen** [libbitcoin/libbitcoin-server#86]
Is there an existing way of making libbitcoinserver connections via the Tor network?

**Comment by evoskuil** [comment]
No, but this is high on the priority queue for the obelisk protocol. We recently worked with `libzmq` to get SOCKS5 integration in that library. This will allow client connections, but there is some integration required that we haven't had to to implement. We haven't considered doing this for the p2p protocol.

**Comment by venzen** [comment]
Yes, I guess block and message exchanges in the p2p protocol are just too frequent for onion routing to be practical. It's the txs that should be obscured and kept anonymous and having those isolated via Tor will be a great step forward.

Appreciate your choice to go with zeromq. I have libbitcoin-server up and running (testnet) and happy with it, as well as the strong BX toolkit. Excellent project.

**Comment by evoskuil** [comment]
Thanks for the feedback. We still have some issues to resolve in server networking, hopefully that will be resolved soon.

**Comment by venzen** [comment]
May I ask about the networking issue specifics? Perhaps they're documented or discussed somewhere and I could look if it's in my capacity to contribute?

**Comment by evoskuil** [comment]
@venzen Sure, always looking for help. I need to create a new issue to document the problem, now that it is better understood. There has been discussion of it on the libbitcoin mailing list.

**Comment by RojavaCrypto** [comment]
There's 3 issues with Tor in the Bitcoin networking layer:

* Timing attacks used for demasking nodes.

* Using the Bitcoin node blacklisting to block Tor nodes making them susceptible to sybil attacks.

* If you only connect to hidden services to mitigate the above problem, then you run the risk of being split into small islands which can be fed fake blocks or transactions, and generally manipulated.

Torifying the server <-> client wallet protocol is another thing, and definitely a good idea. @evoskuil says that SOCKS5 support has been added to zeromq, so we simply have to activate/wait for that feature in libbitcoin server.

As for Tor on the network layer; server <-> Bitcoin network, that's another discussion and opens up potential attacks which is a shame.

**Comment by RojavaCrypto** [comment]
When is ZMQ going to get SOCKS5 support, and does it exist in the current master? This is a very cool feature.

**Comment by evoskuil** [comment]
It's been implemented in zeromq for over a year. It's considered experimental.

**Comment by evoskuil** [comment]
Closing this issue as the functionality is verified.
