### ISSUE TITLE
FYSA: libbitcoin-server (install.sh); Inquiring number of VMs on Mac 

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-server#91]
OS=\`uname -s\`
if [[ $TRAVIS == true ]]; then
    PARALLEL=$SEQUENTIAL
elif [[ $OS == Linux ]]; then
    PARALLEL=\`nproc\`
elif [[ $OS == Darwin ]]; then
    PARALLEL=\`sysctl -n hw.ncpu\`   <= used to inquire number of core VMs on Darwin OSX that can be applied for parallelizing make jobs

**Comment by evoskuil** [comment]
Thanks, I'll get this into libbitcoin-build.

**Comment by evoskuil** [comment]
Moved to libbitcoin-build.

**Comment by evoskuil** [comment]
Implemented
