### ISSUE TITLE
Issue with bitcoin-server functioning properly when compiled for testnet

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-server#92]
Used the following to build an Obelisk server for the testnet:

% ./install.sh --prefix=/Users/XXX/Projects/BX/bitcoin-server/test --build-dir=/Users/XXX/Projects/BX/bitcoin-server/build --with-boost=/Users/XXX/Projects/BX/boost/1.54.0 --without-consensus --enable-testnet

The server tries to establish connections on port 8333 instead of 18333.

% ./test/bin/bs bs-testnet.cfg
Using config file: "bs-testnet.cfg"
Press CTRL-C to stop server.
INFO [worker]: worker ready
INFO [database]: Mapping: "blockchain/blocks_lookup"
INFO [database]: Mapping: "blockchain/blocks_rows"
INFO [database]: Mapping: "blockchain/spends"
INFO [database]: Mapping: "blockchain/txs"
INFO [database]: Mapping: "blockchain/history_lookup"
INFO [database]: Mapping: "blockchain/history_rows"
INFO [database]: Mapping: "blockchain/stealth_index"
INFO [database]: Mapping: "blockchain/stealth_rows"
INFO [database]: Mapping: "blockchain/blocks_lookup"
INFO [database]: Mapping: "blockchain/blocks_rows"
INFO [database]: Mapping: "blockchain/spends"
INFO [database]: Mapping: "blockchain/txs"
INFO [database]: Mapping: "blockchain/history_lookup"
INFO [database]: Mapping: "blockchain/history_rows"
INFO [database]: Mapping: "blockchain/stealth_index"
INFO [database]: Mapping: "blockchain/stealth_rows"
23:32:17.415758 FATAL [node] ================= Startup =================
23:32:17.416564 ERROR [node] ================= Startup =================
23:32:17.416792 INFO [node] ================= Startup =================
23:32:17.419177 INFO [session] Set start height (0)
Server started.
23:32:17.645649 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:32:17.821733 INFO [network] Channel failure [88.112.146.73:8333] unable to reach remote host (boost code 2)
23:32:21.633041 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:32:22.483576 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:32:22.488846 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:32:32.667072 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:32:32.707722 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:32:43.778840 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:32:47.599534 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:32:52.860946 INFO [network] Channel failure [0.0.0.0:0] unable to reach remote host (boost code 2)
23:33:04.061238 INFO [network] Channel failure [82.192.64.136:8333] unable to reach remote host (boost code 2)
23:33:17.536704 INFO [network] Channel timeout [52.24.1.217:8333]
23:33:17.911306 INFO [network] Channel timeout [68.102.107.108:8333]
23:33:22.690015 INFO [network] Channel timeout [207.58.177.193:8333]
23:33:26.990805 INFO [network] Channel timeout [128.199.251.163:8333]

**Comment by evoskuil** [comment]
delete your hosts (peers) file

**Comment by skaht** [comment]
You were right:-) Removing the "hosts" and "peers" file residue from running an older mainnet bitcoin-server fixed my problem.
